//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_IOPC_Alarm_AlarmType
    {
        public Dim_IOPC_Alarm_AlarmType()
        {
            this.Fact_IOPC_Alarm = new HashSet<Fact_IOPC_Alarm>();
        }
    
        public int AlarmTypeID { get; set; }
        public int AlarmTypeID_BK { get; set; }
        public string AlarmType { get; set; }
    
        public virtual ICollection<Fact_IOPC_Alarm> Fact_IOPC_Alarm { get; set; }
    }
}
