//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_POS_Site
    {
        public Dim_POS_Site()
        {
            this.Fact_IOPC_Alarm = new HashSet<Fact_IOPC_Alarm>();
            this.Fact_IOPC_Count = new HashSet<Fact_IOPC_Count>();
            this.Fact_IOPC_DriveThrough = new HashSet<Fact_IOPC_DriveThrough>();
            this.Fact_IOPC_QTime = new HashSet<Fact_IOPC_QTime>();
            this.Fact_IOPC_TrafficCount = new HashSet<Fact_IOPC_TrafficCount>();
            this.Fact_POS_RetailExtraNumber = new HashSet<Fact_POS_RetailExtraNumber>();
            this.Fact_POS_RetailExtraString = new HashSet<Fact_POS_RetailExtraString>();
            this.Fact_POS_Transact = new HashSet<Fact_POS_Transact>();
            this.Fact_POS_TransactTax = new HashSet<Fact_POS_TransactTax>();
            this.Fact_POS_TransExtraNumber = new HashSet<Fact_POS_TransExtraNumber>();
            this.Fact_POS_TransExtraString = new HashSet<Fact_POS_TransExtraString>();
            this.Fact_POS_TransactPayment = new HashSet<Fact_POS_TransactPayment>();
            this.Fact_IOPC_LPR_Info = new HashSet<Fact_IOPC_LPR_Info>();
        }
    
        public int siteKey { get; set; }
        public int siteKey_BK { get; set; }
        public string ServerID { get; set; }
        public string District { get; set; }
        public string Region { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateProvince { get; set; }
        public Nullable<int> Country { get; set; }
        public string PostalZipCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ImageSite { get; set; }
        public string heatMapImage { get; set; }
        public Nullable<short> heatMapX { get; set; }
        public Nullable<short> heatMapY { get; set; }
        public Nullable<int> Syn { get; set; }
        public string HaspkeyID { get; set; }
        public Nullable<int> GoalID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string LandlordCode { get; set; }
        public string LandlordPhone { get; set; }
        public string Address3 { get; set; }
        public string MallCode { get; set; }
        public string Management { get; set; }
        public string MgtPhone { get; set; }
        public string MgtAdress { get; set; }
        public string StoreCategory { get; set; }
        public string StoreType { get; set; }
        public string StoreGroup { get; set; }
        public string StoreDes { get; set; }
        public string FinancialIns { get; set; }
        public string PolicyNo { get; set; }
        public string AccountNo { get; set; }
        public string BranchNo { get; set; }
        public string Address4 { get; set; }
        public string PhoneSite { get; set; }
        public string PhoneFinance { get; set; }
        public string FaxSite { get; set; }
        public string FaxFinance { get; set; }
        public string TlogVersion { get; set; }
        public Nullable<double> SquareFeet { get; set; }
        public Nullable<double> StoreSellingSquareFeet { get; set; }
        public Nullable<decimal> AnnualBudget { get; set; }
        public string ActualBudget { get; set; }
        public Nullable<double> TotalBugetHour { get; set; }
        public Nullable<double> TotalStaffHour { get; set; }
        public Nullable<decimal> SalePerSquareFeet { get; set; }
        public Nullable<double> TotalHourUsed { get; set; }
        public string ManagerASM { get; set; }
        public string Layout { get; set; }
        public string FixturePlan { get; set; }
        public string SecuritySystemCode { get; set; }
        public Nullable<System.DateTime> InstallRemoveDate { get; set; }
        public string SecurityServiceCode { get; set; }
        public Nullable<System.DateTime> ServiceStartDate { get; set; }
        public Nullable<System.DateTime> ServiceEndDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> RemodellingOpenDate { get; set; }
        public Nullable<System.DateTime> RemodellingCloseDate { get; set; }
        public Nullable<System.DateTime> LeaseStartDate { get; set; }
        public Nullable<System.DateTime> LeaseEndDate { get; set; }
        public Nullable<bool> AlertImage { get; set; }
    
        public virtual ICollection<Fact_IOPC_Alarm> Fact_IOPC_Alarm { get; set; }
        public virtual ICollection<Fact_IOPC_Count> Fact_IOPC_Count { get; set; }
        public virtual ICollection<Fact_IOPC_DriveThrough> Fact_IOPC_DriveThrough { get; set; }
        public virtual ICollection<Fact_IOPC_QTime> Fact_IOPC_QTime { get; set; }
        public virtual ICollection<Fact_IOPC_TrafficCount> Fact_IOPC_TrafficCount { get; set; }
        public virtual ICollection<Fact_POS_RetailExtraNumber> Fact_POS_RetailExtraNumber { get; set; }
        public virtual ICollection<Fact_POS_RetailExtraString> Fact_POS_RetailExtraString { get; set; }
        public virtual ICollection<Fact_POS_Transact> Fact_POS_Transact { get; set; }
        public virtual ICollection<Fact_POS_TransactTax> Fact_POS_TransactTax { get; set; }
        public virtual ICollection<Fact_POS_TransExtraNumber> Fact_POS_TransExtraNumber { get; set; }
        public virtual ICollection<Fact_POS_TransExtraString> Fact_POS_TransExtraString { get; set; }
        public virtual ICollection<Fact_POS_TransactPayment> Fact_POS_TransactPayment { get; set; }
        public virtual ICollection<Fact_IOPC_LPR_Info> Fact_IOPC_LPR_Info { get; set; }
    }
}
