//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_POS_Payment
    {
        public Dim_POS_Payment()
        {
            this.Fact_POS_TransactPayment = new HashSet<Fact_POS_TransactPayment>();
        }
    
        public int PaymentID { get; set; }
        public int PaymentID_BK { get; set; }
        public string PaymentName { get; set; }
    
        public virtual ICollection<Fact_POS_TransactPayment> Fact_POS_TransactPayment { get; set; }
    }
}
