//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_POS_Tax
    {
        public Dim_POS_Tax()
        {
            this.Fact_POS_TransactTax = new HashSet<Fact_POS_TransactTax>();
        }
    
        public int TaxID { get; set; }
        public int TaxID_BK { get; set; }
        public string TaxName { get; set; }
    
        public virtual ICollection<Fact_POS_TransactTax> Fact_POS_TransactTax { get; set; }
    }
}
