//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_POS_ItemCode
    {
        public Dim_POS_ItemCode()
        {
            this.Fact_POS_RetailExtraNumber = new HashSet<Fact_POS_RetailExtraNumber>();
            this.Fact_POS_RetailExtraString = new HashSet<Fact_POS_RetailExtraString>();
            this.Fact_POS_Transact = new HashSet<Fact_POS_Transact>();
        }
    
        public int ItemCode_ID { get; set; }
        public int ItemCode_ID_BK { get; set; }
        public string ItemCode_Name { get; set; }
    
        public virtual ICollection<Fact_POS_RetailExtraNumber> Fact_POS_RetailExtraNumber { get; set; }
        public virtual ICollection<Fact_POS_RetailExtraString> Fact_POS_RetailExtraString { get; set; }
        public virtual ICollection<Fact_POS_Transact> Fact_POS_Transact { get; set; }
    }
}
