//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact_IOPC_DriveThrough
    {
        public long TD_ID { get; set; }
        public long TD_ID_BK { get; set; }
        public Nullable<System.DateTime> StartDateKey { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDateKey { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ExternalCamera { get; set; }
        public Nullable<int> InternalCamera { get; set; }
        public int T_PACID { get; set; }
        public Nullable<int> siteKey { get; set; }
        public Nullable<int> Function { get; set; }
    
        public virtual Dim_POS_CameraNB Dim_POS_CameraNB { get; set; }
        public virtual Dim_POS_CameraNB Dim_POS_CameraNB1 { get; set; }
        public virtual Dim_POS_Date Dim_POS_Date { get; set; }
        public virtual Dim_POS_Date Dim_POS_Date1 { get; set; }
        public virtual Dim_POS_PACID Dim_POS_PACID { get; set; }
        public virtual Dim_POS_Site Dim_POS_Site { get; set; }
    }
}
