//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact_IOPC_QTime
    {
        public long EventID { get; set; }
        public long EventID_BK { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<System.DateTime> ServiceEnterTime { get; set; }
        public Nullable<System.DateTime> RegisterEnterTime { get; set; }
        public Nullable<System.DateTime> RegisterExitTime { get; set; }
        public Nullable<System.DateTime> PickupEnterTime { get; set; }
        public Nullable<System.DateTime> PickupExitTime { get; set; }
        public Nullable<System.DateTime> ServiceExitTime { get; set; }
        public Nullable<int> ExternalChannel { get; set; }
        public Nullable<int> InternalChannel { get; set; }
        public int T_PACID { get; set; }
        public Nullable<System.DateTime> DVRDateKey { get; set; }
        public Nullable<int> siteKey { get; set; }
    
        public virtual Dim_POS_CameraNB Dim_POS_CameraNB { get; set; }
        public virtual Dim_POS_CameraNB Dim_POS_CameraNB1 { get; set; }
        public virtual Dim_POS_Date Dim_POS_Date { get; set; }
        public virtual Dim_POS_PACID Dim_POS_PACID { get; set; }
        public virtual Dim_POS_Site Dim_POS_Site { get; set; }
    }
}
