//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact_POS_Periodic_Hourly_Transact
    {
        public int PACID { get; set; }
        public System.DateTime DVRDateKey { get; set; }
        public int TransHour { get; set; }
        public Nullable<int> Count_Trans { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> Count_Trans_N { get; set; }
        public Nullable<decimal> TotalAmount_N { get; set; }
        public Nullable<bool> Normalize { get; set; }
        public Nullable<bool> ReportNormalize { get; set; }
        public Nullable<int> UpdateTimeInt { get; set; }
    
        public virtual Dim_POS_Date Dim_POS_Date { get; set; }
        public virtual Dim_POS_PACID Dim_POS_PACID { get; set; }
    }
}
