//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact_IOPC_Alarm
    {
        public long Alarm_ID { get; set; }
        public long Alarm_ID_BK { get; set; }
        public Nullable<System.DateTime> DVRDateKey { get; set; }
        public Nullable<System.DateTime> DVRDate { get; set; }
        public Nullable<int> A_CameraNumber { get; set; }
        public Nullable<int> MonitoredLocID { get; set; }
        public Nullable<int> ObjectTypeID { get; set; }
        public Nullable<int> AlarmTypeID { get; set; }
        public int T_PACID { get; set; }
        public Nullable<int> siteKey { get; set; }
    
        public virtual Dim_IOPC_Alarm_AlarmType Dim_IOPC_Alarm_AlarmType { get; set; }
        public virtual Dim_IOPC_Monitored_Location Dim_IOPC_Monitored_Location { get; set; }
        public virtual Dim_IOPC_ObjectType Dim_IOPC_ObjectType { get; set; }
        public virtual Dim_POS_CameraNB Dim_POS_CameraNB { get; set; }
        public virtual Dim_POS_Date Dim_POS_Date { get; set; }
        public virtual Dim_POS_PACID Dim_POS_PACID { get; set; }
        public virtual Dim_POS_Site Dim_POS_Site { get; set; }
    }
}
