//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PACDMDB : DbContext
    {
        public PACDMDB()
            : base("name=PACDMDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tAlertEvent> tAlertEvents { get; set; }
        public DbSet<tAlertSeverity> tAlertSeverities { get; set; }
        public DbSet<tAlertType> tAlertTypes { get; set; }
        public DbSet<tAudioSource> tAudioSources { get; set; }
        public DbSet<tBandwidth> tBandwidths { get; set; }
        public DbSet<tbl_ATM_CardNBList> tbl_ATM_CardNBList { get; set; }
        public DbSet<tbl_ATM_ExtraName> tbl_ATM_ExtraName { get; set; }
        public DbSet<tbl_ATM_Trans_XString> tbl_ATM_Trans_XString { get; set; }
        public DbSet<tbl_ATM_Transact> tbl_ATM_Transact { get; set; }
        public DbSet<tbl_ATM_TransCodeList> tbl_ATM_TransCodeList { get; set; }
        public DbSet<tbl_ATM_TransTypeList> tbl_ATM_TransTypeList { get; set; }
        public DbSet<tbl_ATM_XStringList> tbl_ATM_XStringList { get; set; }
        public DbSet<tbl_CA_BatchList> tbl_CA_BatchList { get; set; }
        public DbSet<tbl_CA_CardList> tbl_CA_CardList { get; set; }
        public DbSet<tbl_CA_DevNameList> tbl_CA_DevNameList { get; set; }
        public DbSet<tbl_CA_ExtraName> tbl_CA_ExtraName { get; set; }
        public DbSet<tbl_CA_FullNameList> tbl_CA_FullNameList { get; set; }
        public DbSet<tbl_CA_SiteIDList> tbl_CA_SiteIDList { get; set; }
        public DbSet<tbl_CA_Transact> tbl_CA_Transact { get; set; }
        public DbSet<tbl_CA_TranTypeList> tbl_CA_TranTypeList { get; set; }
        public DbSet<tbl_CA_UnitIDList> tbl_CA_UnitIDList { get; set; }
        public DbSet<tbl_CA_XStringList> tbl_CA_XStringList { get; set; }
        public DbSet<tbl_IOPC_Alarm> tbl_IOPC_Alarm { get; set; }
        public DbSet<tbl_IOPC_AlarmAlarmType> tbl_IOPC_AlarmAlarmType { get; set; }
        public DbSet<tbl_IOPC_AlarmArea> tbl_IOPC_AlarmArea { get; set; }
        public DbSet<tbl_IOPC_AlarmObjectType> tbl_IOPC_AlarmObjectType { get; set; }
        public DbSet<tbl_IOPC_Count> tbl_IOPC_Count { get; set; }
        public DbSet<tbl_IOPC_Count_Area> tbl_IOPC_Count_Area { get; set; }
        public DbSet<tbl_IOPC_Count_ObjectType> tbl_IOPC_Count_ObjectType { get; set; }
        public DbSet<tbl_IOPC_DriveThrough> tbl_IOPC_DriveThrough { get; set; }
        public DbSet<tbl_IOPC_QTime> tbl_IOPC_QTime { get; set; }
        public DbSet<tbl_IOPC_TrafficCount> tbl_IOPC_TrafficCount { get; set; }
        public DbSet<tbl_IOPC_TrafficCountRegion> tbl_IOPC_TrafficCountRegion { get; set; }
        public DbSet<tbl_IOPC_TrafficCountRegionName> tbl_IOPC_TrafficCountRegionName { get; set; }
        public DbSet<tbl_LPR_Info> tbl_LPR_Info { get; set; }
        public DbSet<tbl_POS_CameraNBList> tbl_POS_CameraNBList { get; set; }
        public DbSet<tbl_POS_CardIDList> tbl_POS_CardIDList { get; set; }
        public DbSet<tbl_POS_CheckIDList> tbl_POS_CheckIDList { get; set; }
        public DbSet<tbl_POS_DescriptionList> tbl_POS_DescriptionList { get; set; }
        public DbSet<tbl_POS_ExtraName> tbl_POS_ExtraName { get; set; }
        public DbSet<tbl_POS_ExtraStringValue> tbl_POS_ExtraStringValue { get; set; }
        public DbSet<tbl_POS_ItemCodeList> tbl_POS_ItemCodeList { get; set; }
        public DbSet<tbl_POS_OperatorList> tbl_POS_OperatorList { get; set; }
        public DbSet<tbl_POS_PACID> tbl_POS_PACID { get; set; }
        public DbSet<tbl_POS_PaymentList> tbl_POS_PaymentList { get; set; }
        public DbSet<tbl_POS_RegisterList> tbl_POS_RegisterList { get; set; }
        public DbSet<tbl_POS_Retail> tbl_POS_Retail { get; set; }
        public DbSet<tbl_POS_RetailExtraNumber> tbl_POS_RetailExtraNumber { get; set; }
        public DbSet<tbl_POS_RetailExtraString> tbl_POS_RetailExtraString { get; set; }
        public DbSet<tbl_POS_Sensor> tbl_POS_Sensor { get; set; }
        public DbSet<tbl_POS_ShiftList> tbl_POS_ShiftList { get; set; }
        public DbSet<tbl_POS_StoreList> tbl_POS_StoreList { get; set; }
        public DbSet<tbl_POS_SubRetail> tbl_POS_SubRetail { get; set; }
        public DbSet<tbl_POS_TaxesList> tbl_POS_TaxesList { get; set; }
        public DbSet<tbl_POS_TerminalList> tbl_POS_TerminalList { get; set; }
        public DbSet<tbl_POS_Transact> tbl_POS_Transact { get; set; }
        public DbSet<tbl_POS_TransExtraNumber> tbl_POS_TransExtraNumber { get; set; }
        public DbSet<tbl_POS_TransExtraString> tbl_POS_TransExtraString { get; set; }
        public DbSet<tbl_POS_TransPayment> tbl_POS_TransPayment { get; set; }
        public DbSet<tbl_POS_TransTaxes> tbl_POS_TransTaxes { get; set; }
        
        public DbSet<tbl_WeatherInfo> tbl_WeatherInfo { get; set; }
        public DbSet<tbl_ZipCode> tbl_ZipCode { get; set; }
        
        public DbSet<tCMSConfigPage> tCMSConfigPages { get; set; }
        public DbSet<tCMSDVRSupportVersion> tCMSDVRSupportVersions { get; set; }
        
        public DbSet<tCMSHaspInfo> tCMSHaspInfoes { get; set; }
        public DbSet<tCMSSystemConfig> tCMSSystemConfigs { get; set; }
        public DbSet<tCMSSystemStatus> tCMSSystemStatus { get; set; }
        
        public DbSet<tDateFormat> tDateFormats { get; set; }
        public DbSet<tDVRAddressBook> tDVRAddressBooks { get; set; }
        public DbSet<tDVRAnalogRes> tDVRAnalogRes { get; set; }
        public DbSet<tDVRBackupSchedule> tDVRBackupSchedules { get; set; }
        public DbSet<tDVRBookMark> tDVRBookMarks { get; set; }
        public DbSet<tDVRChangeHistory> tDVRChangeHistories { get; set; }
        public DbSet<tDVRChannels> tDVRChannels { get; set; }
        public DbSet<tDVRConfigChangeTime> tDVRConfigChangeTimes { get; set; }
        public DbSet<tDVRConfigurationBackup> tDVRConfigurationBackups { get; set; }
        public DbSet<tDVRControl> tDVRControls { get; set; }
        public DbSet<tDVRDigitalMonitor> tDVRDigitalMonitors { get; set; }
        public DbSet<tDVRDigitalMonitorChannel> tDVRDigitalMonitorChannels { get; set; }
        public DbSet<tDVRDigitalMonitorOption> tDVRDigitalMonitorOptions { get; set; }
        public DbSet<tDVREmail> tDVREmails { get; set; }
        public DbSet<tDVRHardware> tDVRHardwares { get; set; }
        public DbSet<tDVRIGChannel> tDVRIGChannel { get; set; }
        public DbSet<tDVRIGTrackers> tDVRIGTrackers { get; set; }
        public DbSet<tDVRIOCard> tDVRIOCards { get; set; }
        public DbSet<tDVRIPCameraInputs> tDVRIPCameraInputs { get; set; }
        public DbSet<tDVRIPCameras> tDVRIPCameras { get; set; }
        public DbSet<tDVRIPCameraUsers> tDVRIPCameraUsers { get; set; }
        public DbSet<tDVRIPRes> tDVRIPRes { get; set; }
        public DbSet<tDVRIZChannels> tDVRIZChannels { get; set; }
        public DbSet<tDVRIZTrackers> tDVRIZTrackers { get; set; }
		public DbSet<tDVRKeepAlives> tDVRKeepAlives { get; set; }
        public DbSet<tDVRLDAPGroup> tDVRLDAPGroups { get; set; }
        public DbSet<tDVRLocation> tDVRLocations { get; set; }
        public DbSet<tDVRLogContent> tDVRLogContents { get; set; }
        public DbSet<tDVRLog> tDVRLogs { get; set; }
        public DbSet<tDVRMotionConfig> tDVRMotionConfigs { get; set; }
        public DbSet<tDVRMotionTrackers> tDVRMotionTrackers { get; set; }
        public DbSet<tDVRNetworkCard> tDVRNetworkCards { get; set; }
        public DbSet<tDVRNetwork> tDVRNetworks { get; set; }
        
        public DbSet<tDVROSInfo> tDVROSInfoes { get; set; }
        public DbSet<tDVRRecordSchedule> tDVRRecordSchedules { get; set; }
        public DbSet<tDVRResolutions> tDVRResolutions { get; set; }
        public DbSet<tDVRRestartTime> tDVRRestartTimes { get; set; }
        public DbSet<tDVRRS232Ports> tDVRRS232Ports { get; set; }
        public DbSet<tDVRSensors> tDVRSensors { get; set; }
        public DbSet<tDVRServerInfo> tDVRServerInfoes { get; set; }
        public DbSet<tDVRSetupPages> tDVRSetupPages { get; set; }
        public DbSet<tDVRStorageConfig> tDVRStorageConfigs { get; set; }
        public DbSet<tDVRStorages> tDVRStorages { get; set; }
        public DbSet<tDVRStoreImages> tDVRStoreImages { get; set; }
        public DbSet<tDVRSystemInfo> tDVRSystemInfoes { get; set; }
        public DbSet<tDVRTechnicalLog> tDVRTechnicalLogs { get; set; }
        public DbSet<tDVRTextOverlayChannels> tDVRTextOverlayChannels { get; set; }
        public DbSet<tDVRTextOverlayConfig> tDVRTextOverlayConfigs { get; set; }
        public DbSet<tDVRTextOverlayTrackers> tDVRTextOverlayTrackers { get; set; }
        public DbSet<tDVRTimeAttributes> tDVRTimeAttributes { get; set; }
        public DbSet<tDVRUserConfig> tDVRUserConfigs { get; set; }
        public DbSet<tDVRUserOperation> tDVRUserOperations { get; set; }
        public DbSet<tDVRUserPrivChannel> tDVRUserPrivChannels { get; set; }
        public DbSet<tDVRUserPrivOp> tDVRUserPrivOps { get; set; }
        public DbSet<tDVRUserPrivSetup> tDVRUserPrivSetups { get; set; }
        public DbSet<tDVRUsers> tDVRUsers { get; set; }
        public DbSet<tDVRVCChannels> tDVRVCChannels { get; set; }
        public DbSet<tDVRVCPoints> tDVRVCPoints { get; set; }
        public DbSet<tDVRVCTrackers> tDVRVCTrackers { get; set; }
        public DbSet<tDVRVersion> tDVRVersions { get; set; }
        public DbSet<tDVRVideoSourceImage> tDVRVideoSourceImages { get; set; }
        public DbSet<tDVRVideoSource> tDVRVideoSources { get; set; }
        public DbSet<tDVRVirtualRuler> tDVRVirtualRulers { get; set; }
        public DbSet<tDVRVLChannels> tDVRVLChannels { get; set; }
        public DbSet<tDVRVLPoints> tDVRVLPoints { get; set; }
        public DbSet<tDVRVLTrackers> tDVRVLTrackers { get; set; }
        public DbSet<tDVRVPChannels> tDVRVPChannels { get; set; }
        public DbSet<tDVRVPPoints> tDVRVPPoints { get; set; }
        public DbSet<tDVRVPTrackers> tDVRVPTrackers { get; set; }
        public DbSet<tI3Privileges> tI3Privileges { get; set; }
        public DbSet<tIGActiveTime> tIGActiveTimes { get; set; }
        public DbSet<tIPModel> tIPModels { get; set; }
        public DbSet<tLanguage> tLanguages { get; set; }
        public DbSet<tNetworkType> tNetworkTypes { get; set; }
        public DbSet<tPTZType> tPTZTypes { get; set; }
        public DbSet<tResolutionDef> tResolutionDefs { get; set; }
        public DbSet<tRulerUnit> tRulerUnits { get; set; }
        public DbSet<tSMTPLoginMethod> tSMTPLoginMethods { get; set; }
        
        public DbSet<tSystemTypes> tSystemTypes { get; set; }
        public DbSet<tTimeFormat> tTimeFormats { get; set; }
        public DbSet<tTimeZone> tTimeZones { get; set; }
        public DbSet<tVideoFormat> tVideoFormats { get; set; }
        
        public DbSet<tWeek> tWeeks { get; set; }
        public DbSet<tbl_CA_Trans_XString> tbl_CA_Trans_XString { get; set; }
        public DbSet<tDVRHWDigitalMonitor> tDVRHWDigitalMonitor { get; set; }
    }
}
