//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAlertEvent
    {
        public tAlertEvent()
        {
            this.tCMSWebAlertsMapping = new HashSet<tCMSWebAlertsMapping>();
            this.tDVRStoreImages = new HashSet<tDVRStoreImages>();
            this.tAlertEventLast = new HashSet<tAlertEventLast>();
            this.tAlertEventDetail = new HashSet<tAlertEventDetail>();
        }
    
        public int KAlertEvent { get; set; }
        public byte KAlertType { get; set; }
        public Nullable<int> KDVR { get; set; }
        public Nullable<System.DateTime> TimeZone { get; set; }
        public string DVRUser { get; set; }
        public string Description { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> Channel { get; set; }
        public string CMSUser { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> UpdateTime { get; set; }
        public Nullable<short> Rate { get; set; }
        public string Note { get; set; }
        public string Image { get; set; }
        public Nullable<long> ImageTime { get; set; }
    
        public virtual tAlertType tAlertType { get; set; }
        public virtual ICollection<tCMSWebAlertsMapping> tCMSWebAlertsMapping { get; set; }
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual ICollection<tDVRStoreImages> tDVRStoreImages { get; set; }
        public virtual ICollection<tAlertEventLast> tAlertEventLast { get; set; }
        public virtual ICollection<tAlertEventDetail> tAlertEventDetail { get; set; }
    }
}
