//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAlertType
    {
        public tAlertType()
        {
            this.tAlertEvents = new HashSet<tAlertEvent>();
            this.tCMSWebReport = new HashSet<tCMSWebReport>();
        }
    
        public byte KAlertType { get; set; }
        public byte KAlertSeverity { get; set; }
        public string AlertType { get; set; }
        public Nullable<int> CMSWebType { get; set; }
        public Nullable<int> CMSWebGroup { get; set; }
    
        public virtual ICollection<tAlertEvent> tAlertEvents { get; set; }
        public virtual tAlertSeverity tAlertSeverity { get; set; }
        public virtual ICollection<tCMSWebReport> tCMSWebReport { get; set; }
    }
}
