//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAlertSeverity
    {
        public tAlertSeverity()
        {
            this.tAlertTypes = new HashSet<tAlertType>();
        }
    
        public byte KAlertSeverity { get; set; }
        public string AlertSeverity { get; set; }
    
        public virtual ICollection<tAlertType> tAlertTypes { get; set; }
    }
}
