//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAlertEventDetail
    {
        public int KAlertEvent { get; set; }
        public int KChannel { get; set; }
        public Nullable<int> FixEventID { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> TimeZone { get; set; }
    
        public virtual tAlertEvent tAlertEvent { get; set; }
    }
}
