//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ATM_XStringList
    {
        public tbl_ATM_XStringList()
        {
            this.tbl_ATM_Trans_XString = new HashSet<tbl_ATM_Trans_XString>();
        }
    
        public int XString_ID { get; set; }
        public string XString_Name { get; set; }
    
        public virtual ICollection<tbl_ATM_Trans_XString> tbl_ATM_Trans_XString { get; set; }
    }
}
