//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ATM_Trans_XString
    {
        public long TransID { get; set; }
        public Nullable<int> ExtraNameID { get; set; }
        public int XString_ID { get; set; }
    
        public virtual tbl_ATM_ExtraName tbl_ATM_ExtraName { get; set; }
        public virtual tbl_ATM_Transact tbl_ATM_Transact { get; set; }
        public virtual tbl_ATM_XStringList tbl_ATM_XStringList { get; set; }
    }
}
