//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exception_Criteria
    {
        public tbl_Exception_Criteria()
        {
            this.tbl_Exception_ReportCriteria = new HashSet<tbl_Exception_ReportCriteria>();
        }
    
        public int CriteriaID { get; set; }
        public Nullable<int> ColID { get; set; }
        public string Operator { get; set; }
        public string CriteriaValue_1 { get; set; }
        public string CriteriaValue_2 { get; set; }
    
        public virtual tbl_Exception_ColumnList tbl_Exception_ColumnList { get; set; }
        public virtual ICollection<tbl_Exception_ReportCriteria> tbl_Exception_ReportCriteria { get; set; }
    }
}
