//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_SubRetail
    {
        public long SubRetailID { get; set; }
        public Nullable<long> RetailID { get; set; }
        public Nullable<int> SR_2SubItemLineNb { get; set; }
        public Nullable<double> SR_1Qty { get; set; }
        public Nullable<decimal> SR_0Amount { get; set; }
        public Nullable<int> SR_Description { get; set; }
    
        public virtual tbl_POS_DescriptionList tbl_POS_DescriptionList { get; set; }
        public virtual tbl_POS_Retail tbl_POS_Retail { get; set; }
    }
}
