//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exception_ReportFolders
    {
        public tbl_Exception_ReportFolders()
        {
            this.tbl_Exception_Reports = new HashSet<tbl_Exception_Reports>();
        }
    
        public int FolderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FolderName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
        public virtual ICollection<tbl_Exception_Reports> tbl_Exception_Reports { get; set; }
    }
}
