//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exception_ReportCriteria
    {
        public int ReportID { get; set; }
        public int CriteriaID { get; set; }
        public Nullable<bool> AND_OP { get; set; }
    
        public virtual tbl_Exception_Criteria tbl_Exception_Criteria { get; set; }
        public virtual tbl_Exception_Reports tbl_Exception_Reports { get; set; }
    }
}
