//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IOPC_TrafficCountRegion
    {
        public tbl_IOPC_TrafficCountRegion()
        {
            this.tbl_IOPC_TrafficCount = new HashSet<tbl_IOPC_TrafficCount>();
            this.tbl_IOPC_QueueList = new HashSet<tbl_IOPC_QueueList>();
        }
    
        public int RegionIndex { get; set; }
        public byte RegionID { get; set; }
        public int RegionNameID { get; set; }
        public int InternalChannel { get; set; }
        public int ExternalChannel { get; set; }
        public System.DateTime DVRDate { get; set; }
        public int T_PACID { get; set; }
    
        public virtual ICollection<tbl_IOPC_TrafficCount> tbl_IOPC_TrafficCount { get; set; }
        public virtual tbl_IOPC_TrafficCountRegionName tbl_IOPC_TrafficCountRegionName { get; set; }
        public virtual tbl_POS_CameraNBList tbl_POS_CameraNBList { get; set; }
        public virtual tbl_POS_PACID tbl_POS_PACID { get; set; }
        public virtual ICollection<tbl_IOPC_QueueList> tbl_IOPC_QueueList { get; set; }
    }
}
