//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZipCode
    {
        public tbl_ZipCode()
        {
            this.tbl_WeatherInfo = new HashSet<tbl_WeatherInfo>();
            this.tCMSWebSites = new HashSet<tCMSWebSites>();
        }
    
        public int ZipCodeID { get; set; }
        public string ZipCode { get; set; }
    
        public virtual ICollection<tbl_WeatherInfo> tbl_WeatherInfo { get; set; }
        public virtual ICollection<tCMSWebSites> tCMSWebSites { get; set; }
    }
}
