//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BAM_MetricGroup
    {
        public tbl_BAM_MetricGroup()
        {
            this.tbl_BAM_Metric = new HashSet<tbl_BAM_Metric>();
            this.tbl_BAM_MetricField = new HashSet<tbl_BAM_MetricField>();
            this.tbl_BAM_AdvancedFilter = new HashSet<tbl_BAM_AdvancedFilter>();
            this.tbl_BAM_Metric_ReportList = new HashSet<tbl_BAM_Metric_ReportList>();
        }
    
        public short GroupID { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_BAM_Metric> tbl_BAM_Metric { get; set; }
        public virtual ICollection<tbl_BAM_MetricField> tbl_BAM_MetricField { get; set; }
        public virtual ICollection<tbl_BAM_AdvancedFilter> tbl_BAM_AdvancedFilter { get; set; }
        public virtual ICollection<tbl_BAM_Metric_ReportList> tbl_BAM_Metric_ReportList { get; set; }
    }
}
