//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WeatherInfo
    {
        public int ZipCodeID { get; set; }
        public System.DateTime WeatherDate { get; set; }
        public short Weather_ID { get; set; }
        public short Temp_C { get; set; }
        public short Temp_F { get; set; }
        public Nullable<short> TempM_C { get; set; }
        public Nullable<short> TempM_F { get; set; }
        public Nullable<short> WeatherCode { get; set; }
        public Nullable<short> windspeedMiles { get; set; }
        public Nullable<short> WindSpeedKmph { get; set; }
        public Nullable<short> WindDirDegree { get; set; }
        public string Winddir16Point { get; set; }
        public Nullable<float> PrecipMM { get; set; }
        public Nullable<short> Humidity { get; set; }
        public Nullable<short> Visibility { get; set; }
        public Nullable<short> Pressure { get; set; }
        public string Des_ID { get; set; }
        public Nullable<short> Cloudcover { get; set; }
    
        public virtual tbl_ZipCode tbl_ZipCode { get; set; }
    }
}
