//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IOPC_Count_ObjectType
    {
        public tbl_IOPC_Count_ObjectType()
        {
            this.tbl_IOPC_Count = new HashSet<tbl_IOPC_Count>();
        }
    
        public int ObjectTypeID { get; set; }
        public string ObjectType { get; set; }
    
        public virtual ICollection<tbl_IOPC_Count> tbl_IOPC_Count { get; set; }
    }
}
