//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HM_Actions
    {
        public tbl_HM_Actions()
        {
            this.tbl_HM_ScheduledTasks = new HashSet<tbl_HM_ScheduledTasks>();
        }
    
        public int ActionID { get; set; }
        public string ActionDefinition { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<tbl_HM_ScheduledTasks> tbl_HM_ScheduledTasks { get; set; }
    }
}
