//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exception_ReportColumns
    {
        public int ReportID { get; set; }
        public int ColID { get; set; }
        public Nullable<int> ColWidth { get; set; }
        public Nullable<int> ColOrder { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Ascending { get; set; }
        public Nullable<bool> GroupBy { get; set; }
    
        public virtual tbl_Exception_ColumnList tbl_Exception_ColumnList { get; set; }
        public virtual tbl_Exception_Reports tbl_Exception_Reports { get; set; }
    }
}
