//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BAM_MetricField
    {
        public tbl_BAM_MetricField()
        {
            this.tbl_BAM_MetricGroup = new HashSet<tbl_BAM_MetricGroup>();
        }
    
        public short FieldID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_BAM_MetricGroup> tbl_BAM_MetricGroup { get; set; }
    }
}
