//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BAM_Metric
    {
        public tbl_BAM_Metric()
        {
            this.tbl_BAM_Metric_ReportUser = new HashSet<tbl_BAM_Metric_ReportUser>();
        }
    
        public short MetricID { get; set; }
        public string MetricName { get; set; }
        public Nullable<short> MetricGroupID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Expression { get; set; }
        public string Description { get; set; }
        public string MetricResourceName { get; set; }
        public Nullable<byte> UnitType { get; set; }
        public Nullable<byte> DecimalPlace { get; set; }
        public string CurrencyFormat { get; set; }
        public Nullable<bool> CF_Prefix { get; set; }
    
        public virtual tbl_BAM_MetricGroup tbl_BAM_MetricGroup { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
        public virtual ICollection<tbl_BAM_Metric_ReportUser> tbl_BAM_Metric_ReportUser { get; set; }
    }
}
