//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HM_TaskChannel
    {
        public tbl_HM_TaskChannel()
        {
            this.tbl_HM_Images = new HashSet<tbl_HM_Images>();
        }
    
        public int ProcessID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> KChannel { get; set; }
        public Nullable<System.DateTime> LastExecuted { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<tbl_HM_Images> tbl_HM_Images { get; set; }
        public virtual tbl_HM_ScheduledTasks tbl_HM_ScheduledTasks { get; set; }
        public virtual tDVRChannels tDVRChannels { get; set; }
    }
}
