//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CA_Trans_XString
    {
        public long TransID { get; set; }
        public int XString_ID { get; set; }
        public int ExtraNameID { get; set; }
    
        public virtual tbl_CA_ExtraName tbl_CA_ExtraName { get; set; }
        public virtual tbl_CA_Transact tbl_CA_Transact { get; set; }
        public virtual tbl_CA_XStringList tbl_CA_XStringList { get; set; }
    }
}
