//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IOPC_DriveThrough
    {
        public long TD_ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ExternalCamera { get; set; }
        public int T_PACID { get; set; }
        public Nullable<int> InternalCamera { get; set; }
        public Nullable<int> Function { get; set; }
    
        public virtual tbl_POS_CameraNBList tbl_POS_CameraNBList { get; set; }
        public virtual tbl_POS_PACID tbl_POS_PACID { get; set; }
    }
}
