//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_Labor
    {
        public long EventID { get; set; }
        public int StoreID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int EmployeeID { get; set; }
        public string InPunch { get; set; }
        public string OutPunch { get; set; }
        public int T_PACID { get; set; }
    }
}
