//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_DescriptionList
    {
        public tbl_POS_DescriptionList()
        {
            this.tbl_POS_Retail = new HashSet<tbl_POS_Retail>();
            this.tbl_POS_SubRetail = new HashSet<tbl_POS_SubRetail>();
            this.tbl_Exception_Retail = new HashSet<tbl_Exception_Retail>();
            this.tbl_Exception_SubRetail = new HashSet<tbl_Exception_SubRetail>();
        }
    
        public int Description_ID { get; set; }
        public string Description_Name { get; set; }
    
        public virtual ICollection<tbl_POS_Retail> tbl_POS_Retail { get; set; }
        public virtual ICollection<tbl_POS_SubRetail> tbl_POS_SubRetail { get; set; }
        public virtual ICollection<tbl_Exception_Retail> tbl_Exception_Retail { get; set; }
        public virtual ICollection<tbl_Exception_SubRetail> tbl_Exception_SubRetail { get; set; }
    }
}
