//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_RetailExtraNumber
    {
        public long RetailID { get; set; }
        public int ExtraID { get; set; }
        public Nullable<decimal> ExNum_Value { get; set; }
    
        public virtual tbl_POS_ExtraName tbl_POS_ExtraName { get; set; }
        public virtual tbl_POS_Retail tbl_POS_Retail { get; set; }
    }
}
