//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_TransExtraString
    {
        public long TransID { get; set; }
        public int ExtraID { get; set; }
        public int ExString_ValueID { get; set; }
    
        public virtual tbl_POS_ExtraName tbl_POS_ExtraName { get; set; }
        public virtual tbl_POS_ExtraStringValue tbl_POS_ExtraStringValue { get; set; }
        public virtual tbl_POS_Transact tbl_POS_Transact { get; set; }
    }
}
