//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HM_ScheduledTasks
    {
        public tbl_HM_ScheduledTasks()
        {
            this.tbl_HM_TaskChannel = new HashSet<tbl_HM_TaskChannel>();
        }
    
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public string TaskDesc { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<byte> ScheduleType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastExecuted { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<short> Updated { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual tbl_HM_Actions tbl_HM_Actions { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
        public virtual tbl_HM_ScheduleTypes tbl_HM_ScheduleTypes { get; set; }
        public virtual ICollection<tbl_HM_TaskChannel> tbl_HM_TaskChannel { get; set; }
    }
}
