//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_Sensor
    {
        public long S_ID { get; set; }
        public Nullable<System.DateTime> OT_Start { get; set; }
        public Nullable<System.DateTime> OT_End { get; set; }
        public Nullable<System.DateTime> GT_Start { get; set; }
        public Nullable<System.DateTime> GT_End { get; set; }
        public Nullable<System.DateTime> PU_Start { get; set; }
        public Nullable<System.DateTime> PU_End { get; set; }
        public int T_PACID { get; set; }
        public Nullable<System.DateTime> DVRDate { get; set; }
        public Nullable<System.Guid> S_ID_GUI { get; set; }
    
        public virtual tbl_POS_PACID tbl_POS_PACID { get; set; }
    }
}
