//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_Transact
    {
        public tbl_POS_Transact()
        {
            this.tbl_POS_Retail = new HashSet<tbl_POS_Retail>();
            this.tbl_POS_TransExtraNumber = new HashSet<tbl_POS_TransExtraNumber>();
            this.tbl_POS_TransExtraString = new HashSet<tbl_POS_TransExtraString>();
            this.tbl_POS_TransTaxes = new HashSet<tbl_POS_TransTaxes>();
            this.tbl_POS_TransPayment = new HashSet<tbl_POS_TransPayment>();
        }
    
        public long TransID { get; set; }
        public string TransactKey { get; set; }
        public Nullable<long> T_0TransNB { get; set; }
        public Nullable<decimal> T_6TotalAmount { get; set; }
        public Nullable<decimal> T_1SubTotal { get; set; }
        public Nullable<decimal> T_8ChangeAmount { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> DVRDate { get; set; }
        public Nullable<int> T_9RecItemCount { get; set; }
        public Nullable<int> T_CameraNB { get; set; }
        public Nullable<int> T_OperatorID { get; set; }
        public Nullable<int> T_StoreID { get; set; }
        public Nullable<int> T_TerminalID { get; set; }
        public Nullable<int> T_RegisterID { get; set; }
        public Nullable<int> T_ShiftID { get; set; }
        public Nullable<int> T_CheckID { get; set; }
        public Nullable<int> T_CardID { get; set; }
        public Nullable<int> T_TOBox { get; set; }
        public string T_00TransNBText { get; set; }
        public int T_PACID { get; set; }
    
        public virtual tbl_POS_CameraNBList tbl_POS_CameraNBList { get; set; }
        public virtual tbl_POS_CardIDList tbl_POS_CardIDList { get; set; }
        public virtual tbl_POS_CheckIDList tbl_POS_CheckIDList { get; set; }
        public virtual tbl_POS_OperatorList tbl_POS_OperatorList { get; set; }
        public virtual tbl_POS_PACID tbl_POS_PACID { get; set; }
        public virtual tbl_POS_RegisterList tbl_POS_RegisterList { get; set; }
        public virtual ICollection<tbl_POS_Retail> tbl_POS_Retail { get; set; }
        public virtual tbl_POS_ShiftList tbl_POS_ShiftList { get; set; }
        public virtual tbl_POS_StoreList tbl_POS_StoreList { get; set; }
        public virtual tbl_POS_TerminalList tbl_POS_TerminalList { get; set; }
        public virtual ICollection<tbl_POS_TransExtraNumber> tbl_POS_TransExtraNumber { get; set; }
        public virtual ICollection<tbl_POS_TransExtraString> tbl_POS_TransExtraString { get; set; }
        public virtual ICollection<tbl_POS_TransTaxes> tbl_POS_TransTaxes { get; set; }
        public virtual ICollection<tbl_POS_TransPayment> tbl_POS_TransPayment { get; set; }
    }
}
