//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exception_Type
    {
        public tbl_Exception_Type()
        {
            this.tbl_Exception_FlaggedTrans = new HashSet<tbl_Exception_FlaggedTrans>();
        }
    
        public int TypeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TypeName { get; set; }
        public string TypeDesc { get; set; }
        public Nullable<int> TypeWeight { get; set; }
        public string Color { get; set; }
        public Nullable<bool> Fixed { get; set; }
    
        public virtual ICollection<tbl_Exception_FlaggedTrans> tbl_Exception_FlaggedTrans { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
    }
}
