//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_Retail
    {
        public tbl_POS_Retail()
        {
            this.tbl_POS_RetailExtraNumber = new HashSet<tbl_POS_RetailExtraNumber>();
            this.tbl_POS_RetailExtraString = new HashSet<tbl_POS_RetailExtraString>();
            this.tbl_POS_SubRetail = new HashSet<tbl_POS_SubRetail>();
        }
    
        public long RetailID { get; set; }
        public string RetailKey { get; set; }
        public Nullable<int> R_2ItemLineNb { get; set; }
        public Nullable<double> R_1Qty { get; set; }
        public Nullable<decimal> R_0Amount { get; set; }
        public Nullable<int> R_Description { get; set; }
        public Nullable<int> R_ItemCode { get; set; }
        public Nullable<System.DateTime> R_DVRDate { get; set; }
        public Nullable<long> TransID { get; set; }
        public Nullable<int> R_TOBox { get; set; }
    
        public virtual tbl_POS_DescriptionList tbl_POS_DescriptionList { get; set; }
        public virtual tbl_POS_ItemCodeList tbl_POS_ItemCodeList { get; set; }
        public virtual tbl_POS_Transact tbl_POS_Transact { get; set; }
        public virtual ICollection<tbl_POS_RetailExtraNumber> tbl_POS_RetailExtraNumber { get; set; }
        public virtual ICollection<tbl_POS_RetailExtraString> tbl_POS_RetailExtraString { get; set; }
        public virtual ICollection<tbl_POS_SubRetail> tbl_POS_SubRetail { get; set; }
    }
}
