//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CA_Transact
    {
        public tbl_CA_Transact()
        {
            this.tbl_CA_Trans_XString = new HashSet<tbl_CA_Trans_XString>();
        }
    
        public long TransID { get; set; }
        public long Transact_Key { get; set; }
        public Nullable<System.DateTime> DVRDate { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> T_CameraNB { get; set; }
        public Nullable<int> T_PACID { get; set; }
        public Nullable<int> T_TranType { get; set; }
        public Nullable<int> T_UnitID { get; set; }
        public Nullable<int> T_SiteID { get; set; }
        public Nullable<int> T_DevName { get; set; }
        public Nullable<int> T_Batch { get; set; }
        public Nullable<int> T_Card { get; set; }
        public Nullable<int> T_FullName { get; set; }
    
        public virtual tbl_CA_BatchList tbl_CA_BatchList { get; set; }
        public virtual tbl_CA_CardList tbl_CA_CardList { get; set; }
        public virtual tbl_CA_DevNameList tbl_CA_DevNameList { get; set; }
        public virtual tbl_CA_FullNameList tbl_CA_FullNameList { get; set; }
        public virtual tbl_CA_SiteIDList tbl_CA_SiteIDList { get; set; }
        public virtual ICollection<tbl_CA_Trans_XString> tbl_CA_Trans_XString { get; set; }
        public virtual tbl_CA_TranTypeList tbl_CA_TranTypeList { get; set; }
        public virtual tbl_CA_UnitIDList tbl_CA_UnitIDList { get; set; }
        public virtual tbl_POS_CameraNBList tbl_POS_CameraNBList { get; set; }
        public virtual tbl_POS_PACID tbl_POS_PACID { get; set; }
    }
}
