//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exception_ColumnList
    {
        public tbl_Exception_ColumnList()
        {
            this.tbl_Exception_Criteria = new HashSet<tbl_Exception_Criteria>();
            this.tbl_Exception_ReportColumns = new HashSet<tbl_Exception_ReportColumns>();
        }
    
        public int ColID { get; set; }
        public string ColName { get; set; }
        public string ColDesc { get; set; }
        public string TableName { get; set; }
        public string DataField { get; set; }
        public string DataType { get; set; }
        public string DisplayField { get; set; }
        public Nullable<bool> Sortable { get; set; }
        public Nullable<bool> Groupable { get; set; }
        public Nullable<bool> ShowList { get; set; }
    
        public virtual ICollection<tbl_Exception_Criteria> tbl_Exception_Criteria { get; set; }
        public virtual ICollection<tbl_Exception_ReportColumns> tbl_Exception_ReportColumns { get; set; }
    }
}
