//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ATM_Transact
    {
        public tbl_ATM_Transact()
        {
            this.tbl_ATM_Trans_XString = new HashSet<tbl_ATM_Trans_XString>();
        }
    
        public long TransID { get; set; }
        public string TransactKey { get; set; }
        public Nullable<long> T_0TransNB { get; set; }
        public Nullable<int> T_TransCode { get; set; }
        public Nullable<decimal> T_TransAmount { get; set; }
        public Nullable<decimal> T_TransTermFee { get; set; }
        public Nullable<int> T_TransType { get; set; }
        public Nullable<decimal> T_TransTotal { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string BusinessDate { get; set; }
        public Nullable<System.DateTime> DVRDate { get; set; }
        public Nullable<int> T_CameraNB { get; set; }
        public Nullable<int> T_CardNB { get; set; }
        public Nullable<decimal> T_AcctBalance { get; set; }
        public int T_PACID { get; set; }
    
        public virtual tbl_ATM_CardNBList tbl_ATM_CardNBList { get; set; }
        public virtual ICollection<tbl_ATM_Trans_XString> tbl_ATM_Trans_XString { get; set; }
        public virtual tbl_ATM_TransCodeList tbl_ATM_TransCodeList { get; set; }
        public virtual tbl_ATM_TransTypeList tbl_ATM_TransTypeList { get; set; }
        public virtual tbl_POS_CameraNBList tbl_POS_CameraNBList { get; set; }
        public virtual tbl_POS_PACID tbl_POS_PACID { get; set; }
    }
}
