//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HM_ImageProperties
    {
        public tbl_HM_ImageProperties()
        {
            this.tbl_HM_Images = new HashSet<tbl_HM_Images>();
        }
    
        public int ProID { get; set; }
        public string ProName { get; set; }
        public string ProDesc { get; set; }
        public Nullable<int> ProValue { get; set; }
    
        public virtual ICollection<tbl_HM_Images> tbl_HM_Images { get; set; }
    }
}
