//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exception_Transact
    {
        public tbl_Exception_Transact()
        {
            this.tbl_Exception_FlaggedTrans = new HashSet<tbl_Exception_FlaggedTrans>();
            this.tbl_Exception_Notes = new HashSet<tbl_Exception_Notes>();
            this.tbl_Exception_Retail = new HashSet<tbl_Exception_Retail>();
            this.tbl_Exception_TransPayment = new HashSet<tbl_Exception_TransPayment>();
            this.tbl_Exception_TransTaxes = new HashSet<tbl_Exception_TransTaxes>();
        }
    
        public long TransID { get; set; }
        public string TransactKey { get; set; }
        public Nullable<long> T_0TransNB { get; set; }
        public Nullable<decimal> T_6TotalAmount { get; set; }
        public Nullable<decimal> T_1SubTotal { get; set; }
        public Nullable<decimal> T_8ChangeAmount { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> DVRDate { get; set; }
        public Nullable<int> T_9RecItemCount { get; set; }
        public Nullable<int> T_CameraNB { get; set; }
        public Nullable<int> T_OperatorID { get; set; }
        public Nullable<int> T_StoreID { get; set; }
        public Nullable<int> T_TerminalID { get; set; }
        public Nullable<int> T_RegisterID { get; set; }
        public Nullable<int> T_ShiftID { get; set; }
        public Nullable<int> T_CheckID { get; set; }
        public Nullable<int> T_CardID { get; set; }
        public Nullable<int> T_TOBox { get; set; }
        public string T_00TransNBText { get; set; }
        public Nullable<int> T_PACID { get; set; }
    
        public virtual ICollection<tbl_Exception_FlaggedTrans> tbl_Exception_FlaggedTrans { get; set; }
        public virtual ICollection<tbl_Exception_Notes> tbl_Exception_Notes { get; set; }
        public virtual ICollection<tbl_Exception_Retail> tbl_Exception_Retail { get; set; }
        public virtual tbl_POS_CameraNBList tbl_POS_CameraNBList { get; set; }
        public virtual tbl_POS_CardIDList tbl_POS_CardIDList { get; set; }
        public virtual tbl_POS_CheckIDList tbl_POS_CheckIDList { get; set; }
        public virtual tbl_POS_OperatorList tbl_POS_OperatorList { get; set; }
        public virtual tbl_POS_PACID tbl_POS_PACID { get; set; }
        public virtual tbl_POS_RegisterList tbl_POS_RegisterList { get; set; }
        public virtual tbl_POS_ShiftList tbl_POS_ShiftList { get; set; }
        public virtual tbl_POS_StoreList tbl_POS_StoreList { get; set; }
        public virtual tbl_POS_TerminalList tbl_POS_TerminalList { get; set; }
        public virtual ICollection<tbl_Exception_TransPayment> tbl_Exception_TransPayment { get; set; }
        public virtual ICollection<tbl_Exception_TransTaxes> tbl_Exception_TransTaxes { get; set; }
    }
}
