//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CA_ExtraName
    {
        public tbl_CA_ExtraName()
        {
            this.tbl_CA_Trans_XString = new HashSet<tbl_CA_Trans_XString>();
        }
    
        public int ExtraID { get; set; }
        public string ExtraName { get; set; }
    
        public virtual ICollection<tbl_CA_Trans_XString> tbl_CA_Trans_XString { get; set; }
    }
}
