//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HM_Images
    {
        public tbl_HM_Images()
        {
            this.tbl_HM_ImageNotes = new HashSet<tbl_HM_ImageNotes>();
            this.tbl_HM_ImageProperties = new HashSet<tbl_HM_ImageProperties>();
        }
    
        public long ImgID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public string ImgName { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public string ImgTitle { get; set; }
    
        public virtual ICollection<tbl_HM_ImageNotes> tbl_HM_ImageNotes { get; set; }
        public virtual tbl_HM_TaskChannel tbl_HM_TaskChannel { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
        public virtual ICollection<tbl_HM_ImageProperties> tbl_HM_ImageProperties { get; set; }
    }
}
