//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IOPC_TrafficCountRegionName
    {
        public tbl_IOPC_TrafficCountRegionName()
        {
            this.tbl_IOPC_TrafficCountRegion = new HashSet<tbl_IOPC_TrafficCountRegion>();
        }
    
        public int RegionNameID { get; set; }
        public string RegionName { get; set; }
    
        public virtual ICollection<tbl_IOPC_TrafficCountRegion> tbl_IOPC_TrafficCountRegion { get; set; }
    }
}
