//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HM_ScheduleTypes
    {
        public tbl_HM_ScheduleTypes()
        {
            this.tbl_HM_ScheduledTasks = new HashSet<tbl_HM_ScheduledTasks>();
        }
    
        public byte TypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<tbl_HM_ScheduledTasks> tbl_HM_ScheduledTasks { get; set; }
    }
}
