//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CA_CardList
    {
        public tbl_CA_CardList()
        {
            this.tbl_CA_Transact = new HashSet<tbl_CA_Transact>();
        }
    
        public int Card_ID { get; set; }
        public string Card_Name { get; set; }
    
        public virtual ICollection<tbl_CA_Transact> tbl_CA_Transact { get; set; }
    }
}
