//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BAM_Metric_ReportList
    {
        public tbl_BAM_Metric_ReportList()
        {
            this.tbl_BAM_Metric_ReportUser = new HashSet<tbl_BAM_Metric_ReportUser>();
        }
    
        public short ReportID { get; set; }
        public string ReportName { get; set; }
        public Nullable<short> MetricGroupID { get; set; }
        public string ReportResourceName { get; set; }
        public string ReportLocation { get; set; }
        public string ServiceName { get; set; }
    
        public virtual tbl_BAM_MetricGroup tbl_BAM_MetricGroup { get; set; }
        public virtual ICollection<tbl_BAM_Metric_ReportUser> tbl_BAM_Metric_ReportUser { get; set; }
    }
}
