//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_PACID
    {
        public tbl_POS_PACID()
        {
            this.tbl_ATM_Transact = new HashSet<tbl_ATM_Transact>();
            this.tbl_CA_Transact = new HashSet<tbl_CA_Transact>();
            this.tbl_IOPC_Alarm = new HashSet<tbl_IOPC_Alarm>();
            this.tbl_IOPC_Count = new HashSet<tbl_IOPC_Count>();
            this.tbl_IOPC_DriveThrough = new HashSet<tbl_IOPC_DriveThrough>();
            this.tbl_IOPC_QTime = new HashSet<tbl_IOPC_QTime>();
            this.tbl_LPR_Info = new HashSet<tbl_LPR_Info>();
            this.tbl_POS_Sensor = new HashSet<tbl_POS_Sensor>();
            this.tbl_POS_Transact = new HashSet<tbl_POS_Transact>();
            this.tbl_IOPC_TrafficCountRegion = new HashSet<tbl_IOPC_TrafficCountRegion>();
            this.tbl_Exception_Transact = new HashSet<tbl_Exception_Transact>();
        }
    
        public int KDVR { get; set; }
        public string PACID_Name { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public bool Stop_Convert { get; set; }
        public bool Updated_ConvertInfo { get; set; }
        public Nullable<System.DateTime> Last_Convert { get; set; }
        public string SPK_KeyID { get; set; }
    
        public virtual ICollection<tbl_ATM_Transact> tbl_ATM_Transact { get; set; }
        public virtual ICollection<tbl_CA_Transact> tbl_CA_Transact { get; set; }
        public virtual ICollection<tbl_IOPC_Alarm> tbl_IOPC_Alarm { get; set; }
        public virtual ICollection<tbl_IOPC_Count> tbl_IOPC_Count { get; set; }
        public virtual ICollection<tbl_IOPC_DriveThrough> tbl_IOPC_DriveThrough { get; set; }
        public virtual ICollection<tbl_IOPC_QTime> tbl_IOPC_QTime { get; set; }
        public virtual ICollection<tbl_LPR_Info> tbl_LPR_Info { get; set; }
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual ICollection<tbl_POS_Sensor> tbl_POS_Sensor { get; set; }
        public virtual ICollection<tbl_POS_Transact> tbl_POS_Transact { get; set; }
        public virtual ICollection<tbl_IOPC_TrafficCountRegion> tbl_IOPC_TrafficCountRegion { get; set; }
        public virtual ICollection<tbl_Exception_Transact> tbl_Exception_Transact { get; set; }
    }
}
