//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_PaymentList
    {
        public tbl_POS_PaymentList()
        {
            this.tbl_POS_TransPayment = new HashSet<tbl_POS_TransPayment>();
            this.tbl_Exception_TransPayment = new HashSet<tbl_Exception_TransPayment>();
        }
    
        public int PaymentID { get; set; }
        public string PaymentName { get; set; }
    
        public virtual ICollection<tbl_POS_TransPayment> tbl_POS_TransPayment { get; set; }
        public virtual ICollection<tbl_Exception_TransPayment> tbl_Exception_TransPayment { get; set; }
    }
}
