//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_DashBoardLayouts
    {
        public tCMSWeb_DashBoardLayouts()
        {
            this.tCMSWeb_DashBoardGroupUsers = new HashSet<tCMSWeb_DashBoardGroupUsers>();
            this.tCMSWeb_DashBoardUsers = new HashSet<tCMSWeb_DashBoardUsers>();
            this.tCMSWeb_DashBoard_WidgetPositions = new HashSet<tCMSWeb_DashBoard_WidgetPositions>();
            this.tCMSWeb_DashBoardUserLevels = new HashSet<tCMSWeb_DashBoardUserLevels>();
        }
    
        public int DshLayoutID { get; set; }
        public string DshLayoutName { get; set; }
        public string DshLayoutDescription { get; set; }
        public Nullable<short> DshLayoutType { get; set; }
        public string DshLayoutImage { get; set; }
    
        public virtual ICollection<tCMSWeb_DashBoardGroupUsers> tCMSWeb_DashBoardGroupUsers { get; set; }
        public virtual ICollection<tCMSWeb_DashBoardUsers> tCMSWeb_DashBoardUsers { get; set; }
        public virtual ICollection<tCMSWeb_DashBoard_WidgetPositions> tCMSWeb_DashBoard_WidgetPositions { get; set; }
        public virtual ICollection<tCMSWeb_DashBoardUserLevels> tCMSWeb_DashBoardUserLevels { get; set; }
    }
}
