//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSSystemStatus
    {
        public int KSystem { get; set; }
        public Nullable<int> PhysicalMem { get; set; }
        public Nullable<int> VirtualMem { get; set; }
        public Nullable<int> CPU { get; set; }
        public Nullable<int> TotalSystemMem { get; set; }
        public Nullable<int> TotalSystemCPU { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int SystemType { get; set; }
    
        public virtual tSystemTypes tSystemTypes { get; set; }
    }
}
