//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSHaspInfo
    {
        public long HaspKey { get; set; }
        public long HaspLicense { get; set; }
        public int MaxSupportedDVRs { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public int ErrorCode { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Description { get; set; }
    }
}
