//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_DashBoard_User_Element
    {
        public int UserID { get; set; }
        public int DshElementID { get; set; }
        public Nullable<bool> DshTmpDisable { get; set; }
        public int DshElementOrder { get; set; }
        public Nullable<int> DshElementStyle { get; set; }
        public int WidgetGroupPositionID { get; set; }
    
        public virtual tCMSWeb_DashBoard_WidgetPositions tCMSWeb_DashBoard_WidgetPositions { get; set; }
        public virtual tCMSWeb_DashBoardElements tCMSWeb_DashBoardElements { get; set; }
        public virtual tCMSWeb_DashBoardStyles tCMSWeb_DashBoardStyles { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
    }
}
