//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_DashBoardStyles
    {
        public tCMSWeb_DashBoardStyles()
        {
            this.tCMSWeb_DashBoard_GroupUser_Element = new HashSet<tCMSWeb_DashBoard_GroupUser_Element>();
            this.tCMSWeb_DashBoard_User_Element = new HashSet<tCMSWeb_DashBoard_User_Element>();
            this.tCMSWeb_DashBoardGroupUsers = new HashSet<tCMSWeb_DashBoardGroupUsers>();
            this.tCMSWeb_DashBoardUsers = new HashSet<tCMSWeb_DashBoardUsers>();
            this.tCMSWeb_DashBoard_UserLevel_Element = new HashSet<tCMSWeb_DashBoard_UserLevel_Element>();
            this.tCMSWeb_DashBoardUserLevels = new HashSet<tCMSWeb_DashBoardUserLevels>();
        }
    
        public int StyleID { get; set; }
        public Nullable<int> Background { get; set; }
        public Nullable<int> FontColor { get; set; }
        public Nullable<int> ETC { get; set; }
    
        public virtual ICollection<tCMSWeb_DashBoard_GroupUser_Element> tCMSWeb_DashBoard_GroupUser_Element { get; set; }
        public virtual ICollection<tCMSWeb_DashBoard_User_Element> tCMSWeb_DashBoard_User_Element { get; set; }
        public virtual ICollection<tCMSWeb_DashBoardGroupUsers> tCMSWeb_DashBoardGroupUsers { get; set; }
        public virtual ICollection<tCMSWeb_DashBoardUsers> tCMSWeb_DashBoardUsers { get; set; }
        public virtual ICollection<tCMSWeb_DashBoard_UserLevel_Element> tCMSWeb_DashBoard_UserLevel_Element { get; set; }
        public virtual ICollection<tCMSWeb_DashBoardUserLevels> tCMSWeb_DashBoardUserLevels { get; set; }
    }
}
