//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_DispositionType
    {
        public tCMSWeb_CM_DispositionType()
        {
            this.tCMSWeb_CM_Disposition = new HashSet<tCMSWeb_CM_Disposition>();
        }
    
        public int DispositionTypeID { get; set; }
        public string DispositionName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_Disposition> tCMSWeb_CM_Disposition { get; set; }
    }
}
