//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_InjuryType
    {
        public tCMSWeb_CM_InjuryType()
        {
            this.tCMSWeb_CM_InjuriedPerson = new HashSet<tCMSWeb_CM_InjuriedPerson>();
            this.tCMSWeb_CM_InjuryInfo = new HashSet<tCMSWeb_CM_InjuryInfo>();
        }
    
        public int InjuryTypeID { get; set; }
        public string InjuryTypeName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_InjuriedPerson> tCMSWeb_CM_InjuriedPerson { get; set; }
        public virtual ICollection<tCMSWeb_CM_InjuryInfo> tCMSWeb_CM_InjuryInfo { get; set; }
    }
}
