//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_CaseEvent
    {
        public tCMSWeb_CM_CaseEvent()
        {
            this.tCMSWeb_CM_CaseLinks = new HashSet<tCMSWeb_CM_CaseLinks>();
            this.tCMSWeb_CM_Events = new HashSet<tCMSWeb_CM_Events>();
        }
    
        public int CaseID { get; set; }
        public int CaseTypeID { get; set; }
        public int CaseOwner { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CaseApprover { get; set; }
        public int CStatusID { get; set; }
        public string Narrative { get; set; }
        public Nullable<int> ContactInfoID { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_CaseLinks> tCMSWeb_CM_CaseLinks { get; set; }
        public virtual ICollection<tCMSWeb_CM_Events> tCMSWeb_CM_Events { get; set; }
        public virtual tCMSWeb_CM_CaseStatus tCMSWeb_CM_CaseStatus { get; set; }
        public virtual tCMSWeb_CM_CaseType tCMSWeb_CM_CaseType { get; set; }
        public virtual tCMSWeb_CM_SubjectInfo tCMSWeb_CM_SubjectInfo { get; set; }
    }
}
