//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_FraudType
    {
        public tCMSWeb_CM_FraudType()
        {
            this.tCMSWeb_CM_DishonestEmployee = new HashSet<tCMSWeb_CM_DishonestEmployee>();
            this.tCMSWeb_CM_LawEnforcement = new HashSet<tCMSWeb_CM_LawEnforcement>();
            this.tCMSWeb_CM_TransactionFraud = new HashSet<tCMSWeb_CM_TransactionFraud>();
        }
    
        public int FraudTypeID { get; set; }
        public string FraudTypeName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_DishonestEmployee> tCMSWeb_CM_DishonestEmployee { get; set; }
        public virtual ICollection<tCMSWeb_CM_LawEnforcement> tCMSWeb_CM_LawEnforcement { get; set; }
        public virtual ICollection<tCMSWeb_CM_TransactionFraud> tCMSWeb_CM_TransactionFraud { get; set; }
    }
}
