//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_BusInterruptionType
    {
        public tCMSWeb_CM_BusInterruptionType()
        {
            this.tCMSWeb_CM_InterruptionInfo = new HashSet<tCMSWeb_CM_InterruptionInfo>();
        }
    
        public int BITypeID { get; set; }
        public string BITypeName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_InterruptionInfo> tCMSWeb_CM_InterruptionInfo { get; set; }
    }
}
