//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_SynUser
    {
        public int SynID { get; set; }
        public string ServerIP { get; set; }
        public string UserID { get; set; }
        public string PassWord { get; set; }
        public bool isSSL { get; set; }
        public int Interval { get; set; }
        public string Time { get; set; }
        public Nullable<System.DateTime> LastSyn { get; set; }
        public bool isEnable { get; set; }
        public bool isForceUpdate { get; set; }
        public int SynType { get; set; }
        public int CreateBy { get; set; }
        public string LastSynresult { get; set; }
    
        public virtual tCMSWeb_SynUser_Types tCMSWeb_SynUser_Types { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
    }
}
