//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_LossInjury_CareTaking
    {
        public int CareTakingID { get; set; }
        public Nullable<int> OfficeUseID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<double> Hoursworked { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<decimal> WageCost { get; set; }
    
        public virtual tCMSWeb_CM_LossInjury_OfficeUse tCMSWeb_CM_LossInjury_OfficeUse { get; set; }
    }
}
