//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_Metric_List
    {
        public tCMSWeb_Metric_List()
        {
            this.tCMSWeb_MetricSiteList = new HashSet<tCMSWeb_MetricSiteList>();
        }
    
        public int MListID { get; set; }
        public string MetricName { get; set; }
        public System.DateTime MListEditedDate { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string MetricMeasure { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<bool> isDefault { get; set; }
    
        public virtual ICollection<tCMSWeb_MetricSiteList> tCMSWeb_MetricSiteList { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
    }
}
