//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWebReportColumns
    {
        public tCMSWebReportColumns()
        {
            this.tCMSWebReportFilter = new HashSet<tCMSWebReportFilter>();
            this.tCMSWebReportSort = new HashSet<tCMSWebReportSort>();
        }
    
        public int Column_ID { get; set; }
        public string Column_Name { get; set; }
        public string Column_Description { get; set; }
        public string Belong_table { get; set; }
        public Nullable<bool> Is_Number { get; set; }
        public Nullable<bool> Is_Sort { get; set; }
    
        public virtual ICollection<tCMSWebReportFilter> tCMSWebReportFilter { get; set; }
        public virtual ICollection<tCMSWebReportSort> tCMSWebReportSort { get; set; }
    }
}
