//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWebReport
    {
        public tCMSWebReport()
        {
            this.tAlertType = new HashSet<tAlertType>();
            this.tCMSWebSites = new HashSet<tCMSWebSites>();
            this.ReportRecipients = new HashSet<tCMSWeb_UserList>();
        }
    
        public int ReportKey { get; set; }
        public int UserKey { get; set; }
        public string ReportName { get; set; }
        public string EmailSubject { get; set; }
        public Nullable<int> FreqTypeID { get; set; }
        public Nullable<int> FreqCount { get; set; }
        public Nullable<System.DateTime> StartRunDate { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public Nullable<bool> EnableEmailReporting { get; set; }
        public string RunTime { get; set; }
        public string BAMReportXML { get; set; }
        public Nullable<int> ReportType { get; set; }
    
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
        public virtual ICollection<tAlertType> tAlertType { get; set; }
        public virtual ICollection<tCMSWebSites> tCMSWebSites { get; set; }
        public virtual ICollection<tCMSWeb_UserList> ReportRecipients { get; set; }
    }
}
