//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_Function_Level
    {
        public tCMSWeb_Function_Level()
        {
            this.tCMSWeb_UserGroups = new HashSet<tCMSWeb_UserGroups>();
        }
    
        public int FunclevelID { get; set; }
        public int FunctionID { get; set; }
        public Nullable<int> LevelID { get; set; }
    
        public virtual tCMSWeb_Functions tCMSWeb_Functions { get; set; }
        public virtual tCMSWeb_Levels tCMSWeb_Levels { get; set; }
        public virtual ICollection<tCMSWeb_UserGroups> tCMSWeb_UserGroups { get; set; }
    }
}
