//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CalendarEvents
    {
        public tCMSWeb_CalendarEvents()
        {
            this.tCMSWebRecipients = new HashSet<tCMSWebRecipients>();
            this.tCMSWebSites = new HashSet<tCMSWebSites>();
        }
    
        public int ECalID { get; set; }
        public string ECalName { get; set; }
        public Nullable<System.DateTime> ECStartDate { get; set; }
        public Nullable<System.DateTime> ECEndDate { get; set; }
        public string ECDescription { get; set; }
        public Nullable<System.DateTime> ECCreatedDate { get; set; }
        public int ECCreatedBy { get; set; }
        public Nullable<int> RemindID { get; set; }
        public Nullable<int> ECColor { get; set; }
        public Nullable<byte> RemindBefore { get; set; }
        public Nullable<bool> EventTrigger { get; set; }
        public Nullable<short> RelatedFunction { get; set; }
        public Nullable<short> ScheduleType { get; set; }
        public Nullable<bool> NormalizeAllSite { get; set; }
        public Nullable<System.DateTime> NormalizeTrigger { get; set; }
    
        public virtual ICollection<tCMSWebRecipients> tCMSWebRecipients { get; set; }
        public virtual ICollection<tCMSWebSites> tCMSWebSites { get; set; }
    }
}
