//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_PoliceInfo
    {
        public tCMSWeb_CM_PoliceInfo()
        {
            this.tCMSWeb_CM_LawEnforcement = new HashSet<tCMSWeb_CM_LawEnforcement>();
        }
    
        public int PoliceInfoID { get; set; }
        public Nullable<System.DateTime> PolContactedTime { get; set; }
        public Nullable<System.DateTime> PolArrivalTime { get; set; }
        public string PolOfficerName { get; set; }
        public string PolOfficerNo { get; set; }
        public string PolOfficerPhone { get; set; }
        public string PolCaseNo { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_LawEnforcement> tCMSWeb_CM_LawEnforcement { get; set; }
    }
}
