//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_CaseLinks
    {
        public int CaseLinkID { get; set; }
        public int RelatingCaseID { get; set; }
        public int RelatedCaseID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual tCMSWeb_CM_CaseEvent tCMSWeb_CM_CaseEvent { get; set; }
    }
}
