//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWebSiteMapAreas
    {
        public int SiteMapAreaKey { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<double> LeftPoint { get; set; }
        public Nullable<double> TopPoint { get; set; }
        public Nullable<long> GUID { get; set; }
    
        public virtual tCMSWebSiteImage tCMSWebSiteImage { get; set; }
    }
}
