//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_PolicyViolationType
    {
        public tCMSWeb_CM_PolicyViolationType()
        {
            this.tCMSWeb_CM_OperationHumanType = new HashSet<tCMSWeb_CM_OperationHumanType>();
        }
    
        public int PolicyViolationTypeID { get; set; }
        public string PolicyViolationTypeName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_OperationHumanType> tCMSWeb_CM_OperationHumanType { get; set; }
    }
}
