//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_EX_Report
    {
        public tCMSWeb_EX_Report()
        {
            this.tCMSWeb_EX_MappingReportFilter = new HashSet<tCMSWeb_EX_MappingReportFilter>();
            this.tCMSWeb_EX_ReportTimeRange = new HashSet<tCMSWeb_EX_ReportTimeRange>();
            this.tCMSWeb_UserList = new HashSet<tCMSWeb_UserList>();
        }
    
        public int ExceptionReportID { get; set; }
        public string ExceptionReportName { get; set; }
        public Nullable<bool> BUsePaymentMethodSearch { get; set; }
        public Nullable<bool> BUseCashSearch { get; set; }
        public Nullable<bool> BFixed { get; set; }
        public string ReportID { get; set; }
        public string ReportType { get; set; }
        public string ReportClass { get; set; }
        public string ReportViewer { get; set; }
        public Nullable<bool> BUseTransDate { get; set; }
        public Nullable<bool> BNoCustomer { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> BDashboardPromotion { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual ICollection<tCMSWeb_EX_MappingReportFilter> tCMSWeb_EX_MappingReportFilter { get; set; }
        public virtual ICollection<tCMSWeb_EX_ReportTimeRange> tCMSWeb_EX_ReportTimeRange { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList_Owner { get; set; }
        public virtual ICollection<tCMSWeb_UserList> tCMSWeb_UserList { get; set; }
    }
}
