//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_Goals
    {
        public tCMSWeb_Goals()
        {
            this.tCMSWeb_GoalType_Map = new HashSet<tCMSWeb_GoalType_Map>();
            this.tCMSWebSites = new HashSet<tCMSWebSites>();
        }
    
        public int GoalID { get; set; }
        public string GoalName { get; set; }
        public Nullable<System.DateTime> GoalLastUpdated { get; set; }
        public Nullable<int> GoalCreateBy { get; set; }
    
        public virtual ICollection<tCMSWeb_GoalType_Map> tCMSWeb_GoalType_Map { get; set; }
        public virtual ICollection<tCMSWebSites> tCMSWebSites { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
    }
}
