//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSDVRSupportVersion
    {
        public int VersionNo { get; set; }
        public int Version { get; set; }
        public int Product { get; set; }
        public string VersionName { get; set; }
    }
}
