//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_Company
    {
        public tCMSWeb_Company()
        {
            this.tCMSSystemConfig = new HashSet<tCMSSystemConfig>();
            this.tCMSWeb_AM_Files = new HashSet<tCMSWeb_AM_Files>();
            this.tCMSWeb_UserList = new HashSet<tCMSWeb_UserList>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public byte[] CompanyLogo { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<tCMSSystemConfig> tCMSSystemConfig { get; set; }
        public virtual ICollection<tCMSWeb_AM_Files> tCMSWeb_AM_Files { get; set; }
        public virtual ICollection<tCMSWeb_UserList> tCMSWeb_UserList { get; set; }
    }
}
