//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_DashBoard_WidgetGroupSize
    {
        public tCMSWeb_DashBoard_WidgetGroupSize()
        {
            this.tCMSWeb_DashBoard_WidgetPositions = new HashSet<tCMSWeb_DashBoard_WidgetPositions>();
            this.tCMSWeb_DashBoardElements = new HashSet<tCMSWeb_DashBoardElements>();
        }
    
        public byte WidgetGroupSizeID { get; set; }
        public string WidgetGroupSize { get; set; }
        public Nullable<byte> NumOfWidgets { get; set; }
        public Nullable<bool> IncludeHeader { get; set; }
    
        public virtual ICollection<tCMSWeb_DashBoard_WidgetPositions> tCMSWeb_DashBoard_WidgetPositions { get; set; }
        public virtual ICollection<tCMSWeb_DashBoardElements> tCMSWeb_DashBoardElements { get; set; }
    }
}
