//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWebSiteImage
    {
        public tCMSWebSiteImage()
        {
            this.tCMSWebSiteMapAreas = new HashSet<tCMSWebSiteMapAreas>();
        }
    
        public int ImageID { get; set; }
        public string ImageSite { get; set; }
        public Nullable<short> mapX { get; set; }
        public Nullable<short> mapY { get; set; }
        public Nullable<int> siteKey { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual tCMSWebSites tCMSWebSites { get; set; }
        public virtual ICollection<tCMSWebSiteMapAreas> tCMSWebSiteMapAreas { get; set; }
    }
}
