//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSConfigPage
    {
        public tCMSConfigPage()
        {
            this.tDVRChangeHistories = new HashSet<tDVRChangeHistory>();
            this.tDVRConfigChangeTimes = new HashSet<tDVRConfigChangeTime>();
            this.tDVRConfigurationBackups = new HashSet<tDVRConfigurationBackup>();
        }
    
        public byte KConfig { get; set; }
        public string ConfigName { get; set; }
    
        public virtual ICollection<tDVRChangeHistory> tDVRChangeHistories { get; set; }
        public virtual ICollection<tDVRConfigChangeTime> tDVRConfigChangeTimes { get; set; }
        public virtual ICollection<tDVRConfigurationBackup> tDVRConfigurationBackups { get; set; }
    }
}
