//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_LossInjury_OfficeUse
    {
        public tCMSWeb_CM_LossInjury_OfficeUse()
        {
            this.tCMSWeb_CM_LossInjury_CareTaking = new HashSet<tCMSWeb_CM_LossInjury_CareTaking>();
            this.tCMSWeb_CM_LossInjury_ContractorCharges = new HashSet<tCMSWeb_CM_LossInjury_ContractorCharges>();
            this.tCMSWeb_CM_LossInjury_SectionOne = new HashSet<tCMSWeb_CM_LossInjury_SectionOne>();
        }
    
        public int OfficeUseID { get; set; }
        public Nullable<bool> ApprovedClaim { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> CostofDamage { get; set; }
        public Nullable<decimal> Recoverable { get; set; }
        public string InsuranceClaimNo { get; set; }
        public Nullable<decimal> TotalLoss { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_LossInjury_CareTaking> tCMSWeb_CM_LossInjury_CareTaking { get; set; }
        public virtual ICollection<tCMSWeb_CM_LossInjury_ContractorCharges> tCMSWeb_CM_LossInjury_ContractorCharges { get; set; }
        public virtual ICollection<tCMSWeb_CM_LossInjury_SectionOne> tCMSWeb_CM_LossInjury_SectionOne { get; set; }
    }
}
