//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_TemplateObjects
    {
        public tCMSWeb_CM_TemplateObjects()
        {
            this.tCMSWeb_CM_FieldsGUI = new HashSet<tCMSWeb_CM_FieldsGUI>();
        }
    
        public short ObjectTypeID { get; set; }
        public string ObjectName { get; set; }
        public string ObjectClassName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_FieldsGUI> tCMSWeb_CM_FieldsGUI { get; set; }
    }
}
