//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_LossType
    {
        public tCMSWeb_CM_LossType()
        {
            this.tCMSWeb_CM_LossInjury_SectionOne = new HashSet<tCMSWeb_CM_LossInjury_SectionOne>();
        }
    
        public int LossTypeID { get; set; }
        public string LossTypeName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_LossInjury_SectionOne> tCMSWeb_CM_LossInjury_SectionOne { get; set; }
    }
}
