//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_AM_FTP
    {
        public tCMSWeb_AM_FTP()
        {
            this.tCMSWeb_AM_Files = new HashSet<tCMSWeb_AM_Files>();
        }
    
        public int FTPID { get; set; }
        public string Name { get; set; }
        public string Host { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool SSL { get; set; }
    
        public virtual ICollection<tCMSWeb_AM_Files> tCMSWeb_AM_Files { get; set; }
    }
}
