//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWebSites
    {
        public tCMSWebSites()
        {
            this.tCMSWeb_WorkingHours = new HashSet<tCMSWeb_WorkingHours>();
            this.tCMSWebBAMHeatMapAreas = new HashSet<tCMSWebBAMHeatMapAreas>();
            this.tCMSWeb_MetricSiteList = new HashSet<tCMSWeb_MetricSiteList>();
            this.tDVRChannels = new HashSet<tDVRChannels>();
            this.tCMSWeb_UserList = new HashSet<tCMSWeb_UserList>();
            this.tCMSWeb_CalendarEvents = new HashSet<tCMSWeb_CalendarEvents>();
            this.tCMSWebSiteImage = new HashSet<tCMSWebSiteImage>();
            this.tCMSWebReport = new HashSet<tCMSWebReport>();
        }
    
        public int siteKey { get; set; }
        public string ServerID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateProvince { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> PostalZipCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RegionKey { get; set; }
        public string ImageSite { get; set; }
        public string heatMapImage { get; set; }
        public Nullable<short> heatMapX { get; set; }
        public Nullable<short> heatMapY { get; set; }
        public string HaspkeyID { get; set; }
        public Nullable<int> GoalID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> Syn { get; set; }
        public string LandlordCode { get; set; }
        public string LandlordPhone { get; set; }
        public string MallCode { get; set; }
        public string Address3 { get; set; }
        public string Management { get; set; }
        public string MgtPhone { get; set; }
        public string MgtAdress { get; set; }
        public string StoreCategory { get; set; }
        public string StoreType { get; set; }
        public string StoreGroup { get; set; }
        public string StoreDes { get; set; }
        public string FinancialIns { get; set; }
        public string PolicyNo { get; set; }
        public string AccountNo { get; set; }
        public string BranchNo { get; set; }
        public string Address4 { get; set; }
        public string PhoneSite { get; set; }
        public string PhoneFinance { get; set; }
        public string FaxSite { get; set; }
        public string FaxFinance { get; set; }
        public string TlogVersion { get; set; }
        public Nullable<double> SquareFeet { get; set; }
        public Nullable<double> StoreSellingSquareFeet { get; set; }
        public Nullable<decimal> AnnualBudget { get; set; }
        public string ActualBudget { get; set; }
        public Nullable<double> TotalBugetHour { get; set; }
        public Nullable<double> TotalStaffHour { get; set; }
        public Nullable<decimal> SalePerSquareFeet { get; set; }
        public Nullable<double> TotalHourUsed { get; set; }
        public string ManagerASM { get; set; }
        public string Layout { get; set; }
        public string FixturePlan { get; set; }
        public string SecuritySystemCode { get; set; }
        public Nullable<System.DateTime> InstallRemoveDate { get; set; }
        public string SecurityServiceCode { get; set; }
        public Nullable<System.DateTime> ServiceStartDate { get; set; }
        public Nullable<System.DateTime> ServiceEndDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> RemodellingOpenDate { get; set; }
        public Nullable<System.DateTime> RemodellingCloseDate { get; set; }
        public Nullable<System.DateTime> LeaseStartDate { get; set; }
        public Nullable<System.DateTime> LeaseEndDate { get; set; }
        public Nullable<bool> AlertImage { get; set; }
    
        public virtual ICollection<tCMSWeb_WorkingHours> tCMSWeb_WorkingHours { get; set; }
        public virtual ICollection<tCMSWebBAMHeatMapAreas> tCMSWebBAMHeatMapAreas { get; set; }
        public virtual ICollection<tCMSWeb_MetricSiteList> tCMSWeb_MetricSiteList { get; set; }
        public virtual countries countries { get; set; }
        public virtual states states { get; set; }
        public virtual tbl_ZipCode tbl_ZipCode { get; set; }
        public virtual tCMSWeb_Goals tCMSWeb_Goals { get; set; }
        public virtual tCMSWebRegion tCMSWebRegion { get; set; }
        public virtual ICollection<tDVRChannels> tDVRChannels { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList_Owner { get; set; }
        public virtual ICollection<tCMSWeb_UserList> tCMSWeb_UserList { get; set; }
        public virtual ICollection<tCMSWeb_CalendarEvents> tCMSWeb_CalendarEvents { get; set; }
        public virtual ICollection<tCMSWebSiteImage> tCMSWebSiteImage { get; set; }
        public virtual ICollection<tCMSWebReport> tCMSWebReport { get; set; }
    }
}
