//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_FiscalYear
    {
        public int FYID { get; set; }
        public string FYName { get; set; }
        public Nullable<int> FYTypesID { get; set; }
        public Nullable<System.DateTime> FYDateStart { get; set; }
        public Nullable<System.DateTime> FYDateEnd { get; set; }
        public Nullable<byte> FYClosest { get; set; }
        public Nullable<int> FYNoOfWeeks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> FYDate { get; set; }
        public string CalendarStyle { get; set; }
    
        public virtual tCMSWeb_FiscalYear_Types tCMSWeb_FiscalYear_Types { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
    }
}
