//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_CashShortage
    {
        public int CashShortageID { get; set; }
        public Nullable<decimal> CashShortAmount { get; set; }
        public Nullable<int> CashShortRegNo { get; set; }
        public Nullable<System.DateTime> CashShortDate { get; set; }
        public Nullable<bool> Resolved { get; set; }
    }
}
