//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWebRecipients
    {
        public tCMSWebRecipients()
        {
            this.tCMSWeb_Audit = new HashSet<tCMSWeb_Audit>();
            this.tCMSWeb_CalendarEvents = new HashSet<tCMSWeb_CalendarEvents>();
        }
    
        public int RecipientID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<tCMSWeb_Audit> tCMSWeb_Audit { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
        public virtual ICollection<tCMSWeb_CalendarEvents> tCMSWeb_CalendarEvents { get; set; }
    }
}
