//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_FieldsGUI
    {
        public tCMSWeb_CM_FieldsGUI()
        {
            this.tCMSWeb_CM_EventMaps = new HashSet<tCMSWeb_CM_EventMaps>();
            this.tCMSWeb_CM_IncidentField = new HashSet<tCMSWeb_CM_IncidentField>();
        }
    
        public int FieldsGUIID { get; set; }
        public string FieldsGUIName { get; set; }
        public Nullable<int> ParentFieldID { get; set; }
        public Nullable<bool> MandatoryField { get; set; }
        public Nullable<short> OrderField { get; set; }
        public Nullable<short> ObjectTypeID { get; set; }
        public Nullable<bool> isFixed { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_EventMaps> tCMSWeb_CM_EventMaps { get; set; }
        public virtual ICollection<tCMSWeb_CM_IncidentField> tCMSWeb_CM_IncidentField { get; set; }
        public virtual tCMSWeb_CM_TemplateObjects tCMSWeb_CM_TemplateObjects { get; set; }
    }
}
