//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_Shoplifting
    {
        public int ShopliftingID { get; set; }
        public Nullable<System.DateTime> TimeFirstObserved { get; set; }
        public Nullable<int> RequestMadeBy { get; set; }
        public string Location { get; set; }
    
        public virtual tCMSWeb_CM_SubjectInfo tCMSWeb_CM_SubjectInfo { get; set; }
    }
}
