//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_UserList
    {
        public tCMSWeb_UserList()
        {
            this.tCMSWeb_Audit = new HashSet<tCMSWeb_Audit>();
            this.tCMSWeb_Audit_Note = new HashSet<tCMSWeb_Audit_Note>();
            this.tCMSWeb_DashBoard_User_Element = new HashSet<tCMSWeb_DashBoard_User_Element>();
            this.tCMSWeb_EX_Report_Childs = new HashSet<tCMSWeb_EX_Report>();
            this.tCMSWeb_FiscalYear = new HashSet<tCMSWeb_FiscalYear>();
            this.tCMSWeb_Goals = new HashSet<tCMSWeb_Goals>();
            this.tCMSWeb_Metric_List = new HashSet<tCMSWeb_Metric_List>();
            this.tCMSWeb_NoteItem = new HashSet<tCMSWeb_NoteItem>();
            this.tCMSWeb_SynUser = new HashSet<tCMSWeb_SynUser>();
            this.tCMSWeb_ToDoListItem = new HashSet<tCMSWeb_ToDoListItem>();
            this.tCMSWeb_UserGroups_Childs = new HashSet<tCMSWeb_UserGroups>();
            this.tCMSWebRecipients = new HashSet<tCMSWebRecipients>();
            this.tCMSWebRegion = new HashSet<tCMSWebRegion>();
            this.tCMSWebReport = new HashSet<tCMSWebReport>();
            this.tCMSWebSites_Childs = new HashSet<tCMSWebSites>();
            this.tCMSWeb_EX_Report = new HashSet<tCMSWeb_EX_Report>();
            this.tCMSWebSites = new HashSet<tCMSWebSites>();
            this.tCMSWeb_UserGroups = new HashSet<tCMSWeb_UserGroups>();
            this.tCMSWeb_UserPosition_Childs = new HashSet<tCMSWeb_UserPosition>();
            this.tbl_BAM_Metric = new HashSet<tbl_BAM_Metric>();
            this.tbl_BAM_AdvancedFilter = new HashSet<tbl_BAM_AdvancedFilter>();
            this.tbl_BAM_Metric_ReportUser = new HashSet<tbl_BAM_Metric_ReportUser>();
            this.tbl_IOPC_QueueList = new HashSet<tbl_IOPC_QueueList>();
            this.tbl_Exception_FlaggedTrans = new HashSet<tbl_Exception_FlaggedTrans>();
            this.tbl_Exception_Notes = new HashSet<tbl_Exception_Notes>();
            this.tbl_Exception_Type = new HashSet<tbl_Exception_Type>();
            this.tbl_HM_ImageNotes = new HashSet<tbl_HM_ImageNotes>();
            this.tbl_HM_Images = new HashSet<tbl_HM_Images>();
            this.tbl_HM_ScheduledTasks = new HashSet<tbl_HM_ScheduledTasks>();
            this.tbl_Exception_ReportAssignment = new HashSet<tbl_Exception_ReportAssignment>();
            this.tbl_Exception_ReportFolders = new HashSet<tbl_Exception_ReportFolders>();
            this.tbl_Exception_Reports = new HashSet<tbl_Exception_Reports>();
            this.tCMSWebReport1 = new HashSet<tCMSWebReport>();
        }
    
        public int UserID { get; set; }
        public int UEmployeeID { get; set; }
        public string UFirstName { get; set; }
        public string ULastName { get; set; }
        public string UTelephone { get; set; }
        public string UEmail { get; set; }
        public string UNote { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string UUsername { get; set; }
        public string UPassword { get; set; }
        public Nullable<System.DateTime> UExpiredDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public bool isAdmin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> EmailTrigger { get; set; }
        public Nullable<bool> EmailDaily { get; set; }
        public Nullable<short> Accepted { get; set; }
        public Nullable<System.DateTime> LastAcceptedTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RenewDate { get; set; }
        public string IntegratorName { get; set; }
        public string UID { get; set; }
        public string UPhoto { get; set; }
    
        public virtual ICollection<tCMSWeb_Audit> tCMSWeb_Audit { get; set; }
        public virtual ICollection<tCMSWeb_Audit_Note> tCMSWeb_Audit_Note { get; set; }
        public virtual ICollection<tCMSWeb_DashBoard_User_Element> tCMSWeb_DashBoard_User_Element { get; set; }
        public virtual tCMSWeb_DashBoardUsers tCMSWeb_DashBoardUsers { get; set; }
        public virtual ICollection<tCMSWeb_EX_Report> tCMSWeb_EX_Report_Childs { get; set; }
        public virtual ICollection<tCMSWeb_FiscalYear> tCMSWeb_FiscalYear { get; set; }
        public virtual ICollection<tCMSWeb_Goals> tCMSWeb_Goals { get; set; }
        public virtual ICollection<tCMSWeb_Metric_List> tCMSWeb_Metric_List { get; set; }
        public virtual ICollection<tCMSWeb_NoteItem> tCMSWeb_NoteItem { get; set; }
        public virtual ICollection<tCMSWeb_SynUser> tCMSWeb_SynUser { get; set; }
        public virtual ICollection<tCMSWeb_ToDoListItem> tCMSWeb_ToDoListItem { get; set; }
        public virtual ICollection<tCMSWeb_UserGroups> tCMSWeb_UserGroups_Childs { get; set; }
        public virtual ICollection<tCMSWebRecipients> tCMSWebRecipients { get; set; }
        public virtual ICollection<tCMSWebRegion> tCMSWebRegion { get; set; }
        public virtual ICollection<tCMSWebReport> tCMSWebReport { get; set; }
        public virtual ICollection<tCMSWebSites> tCMSWebSites_Childs { get; set; }
        public virtual ICollection<tCMSWeb_EX_Report> tCMSWeb_EX_Report { get; set; }
        public virtual ICollection<tCMSWebSites> tCMSWebSites { get; set; }
        public virtual ICollection<tCMSWeb_UserGroups> tCMSWeb_UserGroups { get; set; }
        public virtual ICollection<tCMSWeb_UserPosition> tCMSWeb_UserPosition_Childs { get; set; }
        public virtual tCMSWeb_UserPosition tCMSWeb_UserPosition { get; set; }
        public virtual tCMSWeb_Company tCMSWeb_Company { get; set; }
        public virtual ICollection<tbl_BAM_Metric> tbl_BAM_Metric { get; set; }
        public virtual ICollection<tbl_BAM_AdvancedFilter> tbl_BAM_AdvancedFilter { get; set; }
        public virtual ICollection<tbl_BAM_Metric_ReportUser> tbl_BAM_Metric_ReportUser { get; set; }
        public virtual ICollection<tbl_IOPC_QueueList> tbl_IOPC_QueueList { get; set; }
        public virtual ICollection<tbl_Exception_FlaggedTrans> tbl_Exception_FlaggedTrans { get; set; }
        public virtual ICollection<tbl_Exception_Notes> tbl_Exception_Notes { get; set; }
        public virtual ICollection<tbl_Exception_Type> tbl_Exception_Type { get; set; }
        public virtual ICollection<tbl_HM_ImageNotes> tbl_HM_ImageNotes { get; set; }
        public virtual ICollection<tbl_HM_Images> tbl_HM_Images { get; set; }
        public virtual ICollection<tbl_HM_ScheduledTasks> tbl_HM_ScheduledTasks { get; set; }
        public virtual ICollection<tbl_Exception_ReportAssignment> tbl_Exception_ReportAssignment { get; set; }
        public virtual ICollection<tbl_Exception_ReportFolders> tbl_Exception_ReportFolders { get; set; }
        public virtual ICollection<tbl_Exception_Reports> tbl_Exception_Reports { get; set; }
        public virtual ICollection<tCMSWebReport> tCMSWebReport1 { get; set; }
    }
}
