//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_Goal_Types
    {
        public tCMSWeb_Goal_Types()
        {
            this.tCMSWeb_GoalType_Map = new HashSet<tCMSWeb_GoalType_Map>();
        }
    
        public int GoalTypeID { get; set; }
        public string GoalTypeName { get; set; }
    
        public virtual ICollection<tCMSWeb_GoalType_Map> tCMSWeb_GoalType_Map { get; set; }
    }
}
