//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWebBAMHeatMapAreas
    {
        public int AreaKey { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> PACID { get; set; }
        public Nullable<int> LeftPoint { get; set; }
        public Nullable<int> TopPoint { get; set; }
        public string Points { get; set; }
        public Nullable<int> siteKey { get; set; }
        public long GUID { get; set; }
    
        public virtual tCMSWebSites tCMSWebSites { get; set; }
    }
}
