//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_SubjectDetail
    {
        public tCMSWeb_CM_SubjectDetail()
        {
            this.tCMSWeb_CM_SubjectInfo = new HashSet<tCMSWeb_CM_SubjectInfo>();
        }
    
        public int SubjectDetailID { get; set; }
        public string Witness { get; set; }
        public Nullable<int> AgeClassID { get; set; }
        public Nullable<int> BiologicalInfoID { get; set; }
        public string SSN { get; set; }
        public string Attire { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<int> SubjectTypeID { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public string StateID { get; set; }
        public string Guardian { get; set; }
    
        public virtual tCMSWeb_CM_AgeClasification tCMSWeb_CM_AgeClasification { get; set; }
        public virtual tCMSWeb_CM_BiologicalInfo tCMSWeb_CM_BiologicalInfo { get; set; }
        public virtual ICollection<tCMSWeb_CM_SubjectInfo> tCMSWeb_CM_SubjectInfo { get; set; }
        public virtual tCMSWeb_CM_SubjectType tCMSWeb_CM_SubjectType { get; set; }
    }
}
