//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_ToDoListItem
    {
        public int ToDoListItemID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ToDoListItemContent { get; set; }
        public Nullable<int> ToDoListItemColor { get; set; }
        public string ToDoListItemIcon { get; set; }
        public Nullable<byte> ToDoListItemStatus { get; set; }
        public Nullable<int> ToDoListItemFont { get; set; }
        public Nullable<byte> ToDoListItemUrgency { get; set; }
        public Nullable<short> ToDoListItemRecurrence { get; set; }
        public Nullable<byte> ToDoListItemOrder { get; set; }
    
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
    }
}
