//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_StockInfo
    {
        public tCMSWeb_CM_StockInfo()
        {
            this.tCMSWeb_CM_Merchandise = new HashSet<tCMSWeb_CM_Merchandise>();
        }
    
        public int StockInfoID { get; set; }
        public string StockInfoUPC { get; set; }
        public string StockInfoSKU { get; set; }
        public string Description { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<int> MerchandiseID { get; set; }
    
        public virtual tCMSWeb_CM_Merchandise tCMSWeb_CM_Merchandise_Owner { get; set; }
        public virtual ICollection<tCMSWeb_CM_Merchandise> tCMSWeb_CM_Merchandise { get; set; }
    }
}
