//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_Audit_Note
    {
        public tCMSWeb_Audit_Note()
        {
            this.tCMSWeb_Audit = new HashSet<tCMSWeb_Audit>();
            this.tCMSWeb_Audit_Media = new HashSet<tCMSWeb_Audit_Media>();
        }
    
        public int NoteID { get; set; }
        public Nullable<short> Type { get; set; }
        public string NoteText { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual ICollection<tCMSWeb_Audit> tCMSWeb_Audit { get; set; }
        public virtual ICollection<tCMSWeb_Audit_Media> tCMSWeb_Audit_Media { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
    }
}
