//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_DishonestEmployee
    {
        public int DisEmpID { get; set; }
        public Nullable<System.DateTime> DateOfHire { get; set; }
        public string Position { get; set; }
        public Nullable<bool> FullTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string InvestigationInitiatedBy { get; set; }
        public string InvestigationConductedBy { get; set; }
        public Nullable<decimal> TotalDollar { get; set; }
        public Nullable<decimal> RecoveryDollar { get; set; }
        public Nullable<int> FraudTypeID { get; set; }
    
        public virtual tCMSWeb_CM_FraudType tCMSWeb_CM_FraudType { get; set; }
    }
}
