//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_LossInjury_SectionTwo
    {
        public int SectionTwoID { get; set; }
        public Nullable<int> SectionOneID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Description { get; set; }
        public string Requisition { get; set; }
        public Nullable<decimal> ReplacementCost { get; set; }
    
        public virtual tCMSWeb_CM_LossInjury_SectionOne tCMSWeb_CM_LossInjury_SectionOne { get; set; }
    }
}
