//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_EventAttachments
    {
        public int EventID { get; set; }
        public int SessionID { get; set; }
    
        public virtual tCMSWeb_CM_Events tCMSWeb_CM_Events { get; set; }
    }
}
