//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_CaseDisposition
    {
        public tCMSWeb_CM_CaseDisposition()
        {
            this.tCMSWeb_CM_CourtInfo = new HashSet<tCMSWeb_CM_CourtInfo>();
        }
    
        public int CaseDispositionID { get; set; }
        public string CaseDispositionName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_CourtInfo> tCMSWeb_CM_CourtInfo { get; set; }
    }
}
