//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_Audit_Media
    {
        public tCMSWeb_Audit_Media()
        {
            this.tCMSWeb_Audit = new HashSet<tCMSWeb_Audit>();
        }
    
        public int MediaID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string PhysicalDir { get; set; }
        public string MediaName { get; set; }
        public Nullable<System.DateTime> DVRDateTime { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<System.DateTime> LastViewDateTime { get; set; }
        public string StartAt { get; set; }
        public string EndAt { get; set; }
        public Nullable<short> MediaType { get; set; }
    
        public virtual tCMSWeb_Audit_Note tCMSWeb_Audit_Note { get; set; }
        public virtual ICollection<tCMSWeb_Audit> tCMSWeb_Audit { get; set; }
        public virtual tDVRChannels tDVRChannels { get; set; }
    }
}
