//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_InterviewInfo
    {
        public int IVID { get; set; }
        public string IVWitnessedBy { get; set; }
        public string IVLocation { get; set; }
        public string IVBy { get; set; }
        public Nullable<System.DateTime> IVDate { get; set; }
        public Nullable<System.DateTime> IVStartTime { get; set; }
        public Nullable<System.DateTime> IVEndTime { get; set; }
        public Nullable<bool> IVVideo { get; set; }
        public string IVVerbalDocument { get; set; }
        public string IVWrittenDocument { get; set; }
        public Nullable<bool> IVVerbalAdmission { get; set; }
        public Nullable<bool> IVWrittenAdmission { get; set; }
        public string IVVIdeoLink { get; set; }
        public Nullable<int> EvidenceInfoID { get; set; }
        public string RequestMadeBy { get; set; }
        public string ReasonGiven { get; set; }
    
        public virtual tCMSWeb_CM_EvidenceInfo tCMSWeb_CM_EvidenceInfo { get; set; }
    }
}
