//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_CourtInfo
    {
        public tCMSWeb_CM_CourtInfo()
        {
            this.tCMSWeb_CM_LawEnforcement = new HashSet<tCMSWeb_CM_LawEnforcement>();
        }
    
        public int CourtInfoID { get; set; }
        public string CourtName { get; set; }
        public string CourtLocation { get; set; }
        public Nullable<System.DateTime> CourtDate { get; set; }
        public Nullable<int> CaseDispositionID { get; set; }
        public Nullable<decimal> Restitution { get; set; }
        public Nullable<decimal> CivilDemand { get; set; }
        public string SubjectPlea { get; set; }
        public string Penalty { get; set; }
    
        public virtual tCMSWeb_CM_CaseDisposition tCMSWeb_CM_CaseDisposition { get; set; }
        public virtual ICollection<tCMSWeb_CM_LawEnforcement> tCMSWeb_CM_LawEnforcement { get; set; }
    }
}
