//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_ObjectCondition
    {
        public tCMSWeb_CM_ObjectCondition()
        {
            this.tCMSWeb_CM_Merchandise = new HashSet<tCMSWeb_CM_Merchandise>();
        }
    
        public int ObjectConditionID { get; set; }
        public string ObjectConditionName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_Merchandise> tCMSWeb_CM_Merchandise { get; set; }
    }
}
