//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_MetricSiteList
    {
        public int MListID { get; set; }
        public int SiteID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tCMSWeb_Metric_List tCMSWeb_Metric_List { get; set; }
        public virtual tCMSWebSites tCMSWebSites { get; set; }
    }
}
