//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_LawEnforcement
    {
        public int LawEnforcementID { get; set; }
        public Nullable<int> PoliceInfoID { get; set; }
        public Nullable<int> InvestInfoID { get; set; }
        public Nullable<int> CourtInfoID { get; set; }
        public Nullable<System.DateTime> ApprehendedTime { get; set; }
        public Nullable<bool> Handcuffed { get; set; }
        public Nullable<bool> Trespass { get; set; }
        public Nullable<bool> Prosecuted { get; set; }
        public Nullable<bool> CCTVAvailable { get; set; }
        public Nullable<int> FraudTypeID { get; set; }
    
        public virtual tCMSWeb_CM_CourtInfo tCMSWeb_CM_CourtInfo { get; set; }
        public virtual tCMSWeb_CM_FraudType tCMSWeb_CM_FraudType { get; set; }
        public virtual tCMSWeb_CM_InvestigationInfo tCMSWeb_CM_InvestigationInfo { get; set; }
        public virtual tCMSWeb_CM_PoliceInfo tCMSWeb_CM_PoliceInfo { get; set; }
    }
}
