//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWebRegion
    {
        public tCMSWebRegion()
        {
            this.tCMSWebSites = new HashSet<tCMSWebSites>();
        }
    
        public int RegionKey { get; set; }
        public Nullable<int> UserKey { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> RegionParentID { get; set; }
        public string Description { get; set; }
        public Nullable<byte> synched { get; set; }
    
        public virtual ICollection<tCMSWebSites> tCMSWebSites { get; set; }
        public virtual tCMSWeb_UserList tCMSWeb_UserList { get; set; }
    }
}
