//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_SubjectInfo
    {
        public tCMSWeb_CM_SubjectInfo()
        {
            this.tCMSWeb_CM_CaseEvent = new HashSet<tCMSWeb_CM_CaseEvent>();
            this.tCMSWeb_CM_Events = new HashSet<tCMSWeb_CM_Events>();
            this.tCMSWeb_CM_Shoplifting = new HashSet<tCMSWeb_CM_Shoplifting>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectFirstName { get; set; }
        public string SubjectMiddleName { get; set; }
        public string SubjectLastName { get; set; }
        public string SubjectJobTitle { get; set; }
        public string SubjectHomePhone { get; set; }
        public string SubjectCellPhone { get; set; }
        public string SubjectEmail { get; set; }
        public string SubjectAddrStreet { get; set; }
        public string SubjectAddrCity { get; set; }
        public Nullable<int> SubjectAddrProvince { get; set; }
        public Nullable<int> SubjectAddrCountry { get; set; }
        public string SubjectAddrZIP { get; set; }
        public string SubjectAdditionalInfo { get; set; }
        public Nullable<int> SubjectDetailID { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_CaseEvent> tCMSWeb_CM_CaseEvent { get; set; }
        public virtual ICollection<tCMSWeb_CM_Events> tCMSWeb_CM_Events { get; set; }
        public virtual ICollection<tCMSWeb_CM_Shoplifting> tCMSWeb_CM_Shoplifting { get; set; }
        public virtual tCMSWeb_CM_SubjectDetail tCMSWeb_CM_SubjectDetail { get; set; }
    }
}
