//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_Events
    {
        public tCMSWeb_CM_Events()
        {
            this.tCMSWeb_CM_EventAttachments = new HashSet<tCMSWeb_CM_EventAttachments>();
            this.tCMSWeb_CM_EventMaps = new HashSet<tCMSWeb_CM_EventMaps>();
        }
    
        public int EventID { get; set; }
        public Nullable<int> EventLocation { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string Narrative { get; set; }
        public int CaseID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual tCMSWeb_CM_CaseEvent tCMSWeb_CM_CaseEvent { get; set; }
        public virtual ICollection<tCMSWeb_CM_EventAttachments> tCMSWeb_CM_EventAttachments { get; set; }
        public virtual ICollection<tCMSWeb_CM_EventMaps> tCMSWeb_CM_EventMaps { get; set; }
        public virtual tCMSWeb_CM_SubjectInfo tCMSWeb_CM_SubjectInfo { get; set; }
    }
}
