//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_Disposition
    {
        public tCMSWeb_CM_Disposition()
        {
            this.tCMSWeb_CM_Merchandise = new HashSet<tCMSWeb_CM_Merchandise>();
        }
    
        public int DispositionID { get; set; }
        public Nullable<int> DispositionTypeID { get; set; }
        public Nullable<bool> HeldAsEvidence { get; set; }
        public Nullable<bool> ReturnedToStock { get; set; }
        public Nullable<System.DateTime> DateReturnedToStock { get; set; }
        public string DispositionInfo { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_Merchandise> tCMSWeb_CM_Merchandise { get; set; }
        public virtual tCMSWeb_CM_DispositionType tCMSWeb_CM_DispositionType { get; set; }
    }
}
