//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWebAlertsMapping
    {
        public System.Guid KAlertMapID { get; set; }
        public int KAlertEvent { get; set; }
        public bool Ignored { get; set; }
    
        public virtual tAlertEvent tAlertEvent { get; set; }
    }
}
