//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_GoalType_Map
    {
        public int GoalTypeID { get; set; }
        public int GoalID { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
    
        public virtual tCMSWeb_Goal_Types tCMSWeb_Goal_Types { get; set; }
        public virtual tCMSWeb_Goals tCMSWeb_Goals { get; set; }
    }
}
