//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_SynUser_Types
    {
        public tCMSWeb_SynUser_Types()
        {
            this.tCMSWeb_SynUser = new HashSet<tCMSWeb_SynUser>();
        }
    
        public int SynID { get; set; }
        public string SynName { get; set; }
        public string SynDes { get; set; }
        public string SynConnection { get; set; }
    
        public virtual ICollection<tCMSWeb_SynUser> tCMSWeb_SynUser { get; set; }
    }
}
