//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_InjuriedPerson
    {
        public tCMSWeb_CM_InjuriedPerson()
        {
            this.tCMSWeb_CM_Witness = new HashSet<tCMSWeb_CM_Witness>();
        }
    
        public int InjuriedPersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Address { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string GradeLevel { get; set; }
        public Nullable<bool> Student { get; set; }
        public string ParentGuardian { get; set; }
        public string IdentifyInjury { get; set; }
        public Nullable<System.DateTime> DateTimeEvent { get; set; }
        public Nullable<bool> BodilyInjury { get; set; }
        public string BodyPart { get; set; }
        public string PropertyDamage { get; set; }
        public Nullable<int> InjuryTypeID { get; set; }
        public string InjuryTypeOther { get; set; }
        public Nullable<bool> OnSchoolPremises { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string LocationAddress { get; set; }
        public string Description { get; set; }
        public string NameofSchool { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherLastName { get; set; }
        public string PrincipalFirstName { get; set; }
        public string PrincipalLastName { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public string Other { get; set; }
        public Nullable<int> IdentifyInjuryID { get; set; }
    
        public virtual tCMSWeb_CM_InjuryType tCMSWeb_CM_InjuryType { get; set; }
        public virtual tCMSWeb_CM_InjuryTypeForStudent tCMSWeb_CM_InjuryTypeForStudent { get; set; }
        public virtual tCMSWeb_CM_LocationInjury tCMSWeb_CM_LocationInjury { get; set; }
        public virtual ICollection<tCMSWeb_CM_Witness> tCMSWeb_CM_Witness { get; set; }
    }
}
