//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_DashBoardElements
    {
        public tCMSWeb_DashBoardElements()
        {
            this.tCMSWeb_DashBoard_GroupUser_Element = new HashSet<tCMSWeb_DashBoard_GroupUser_Element>();
            this.tCMSWeb_DashBoard_User_Element = new HashSet<tCMSWeb_DashBoard_User_Element>();
            this.tCMSWeb_DashBoard_UserLevel_Element = new HashSet<tCMSWeb_DashBoard_UserLevel_Element>();
        }
    
        public int DshElementID { get; set; }
        public string DshElementName { get; set; }
        public string DshElementDesc { get; set; }
        public string DshElementURL { get; set; }
        public Nullable<short> DshElementType { get; set; }
        public string DshElemenJS { get; set; }
        public byte DshElementSize { get; set; }
        public Nullable<byte> DshElement_SingleSite { get; set; }
        public string DshParams { get; set; }
    
        public virtual ICollection<tCMSWeb_DashBoard_GroupUser_Element> tCMSWeb_DashBoard_GroupUser_Element { get; set; }
        public virtual ICollection<tCMSWeb_DashBoard_User_Element> tCMSWeb_DashBoard_User_Element { get; set; }
        public virtual tCMSWeb_DashBoard_WidgetGroupSize tCMSWeb_DashBoard_WidgetGroupSize { get; set; }
        public virtual ICollection<tCMSWeb_DashBoard_UserLevel_Element> tCMSWeb_DashBoard_UserLevel_Element { get; set; }
    }
}
