//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_DashBoardGroupUsers
    {
        public int GroupID { get; set; }
        public int DshLayoutID { get; set; }
        public int StyleID { get; set; }
    
        public virtual tCMSWeb_DashBoardLayouts tCMSWeb_DashBoardLayouts { get; set; }
        public virtual tCMSWeb_DashBoardStyles tCMSWeb_DashBoardStyles { get; set; }
    }
}
