//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_InjuryInfo
    {
        public int InjuryID { get; set; }
        public string MedicalTreatment { get; set; }
        public string BodyPartAffected { get; set; }
        public Nullable<System.DateTime> TimeLoss { get; set; }
        public Nullable<int> InjuryTypeID { get; set; }
        public string EmployeeOnTheScene { get; set; }
    
        public virtual tCMSWeb_CM_InjuryType tCMSWeb_CM_InjuryType { get; set; }
    }
}
