//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_Audit_Schedule
    {
        public tCMSWeb_Audit_Schedule()
        {
            this.tCMSWeb_Audit = new HashSet<tCMSWeb_Audit>();
        }
    
        public int ScheduleID { get; set; }
        public Nullable<short> Interval { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<short> MonthMask { get; set; }
        public Nullable<short> EveryNTimes { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
    
        public virtual ICollection<tCMSWeb_Audit> tCMSWeb_Audit { get; set; }
    }
}
