//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_BiologicalInfo
    {
        public tCMSWeb_CM_BiologicalInfo()
        {
            this.tCMSWeb_CM_SubjectDetail = new HashSet<tCMSWeb_CM_SubjectDetail>();
        }
    
        public int BiologicalInfoID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> HairColorTypeID { get; set; }
        public Nullable<int> SkinColorTypeID { get; set; }
        public string EyeColor { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> WeightMeasureTypeID { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<int> HeightMeasureTypeID { get; set; }
        public string Sex { get; set; }
        public string DistinguishingFeature { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_SubjectDetail> tCMSWeb_CM_SubjectDetail { get; set; }
        public virtual tCMSWeb_CM_HairColorType tCMSWeb_CM_HairColorType { get; set; }
        public virtual tCMSWeb_CM_HeightMeasureType tCMSWeb_CM_HeightMeasureType { get; set; }
        public virtual tCMSWeb_CM_SkinColorType tCMSWeb_CM_SkinColorType { get; set; }
        public virtual tCMSWeb_CM_WeightMeasureType tCMSWeb_CM_WeightMeasureType { get; set; }
    }
}
