//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_TransactionInfo
    {
        public tCMSWeb_CM_TransactionInfo()
        {
            this.tCMSWeb_CM_TransactionFraud = new HashSet<tCMSWeb_CM_TransactionFraud>();
        }
    
        public int CaseTransactID { get; set; }
        public Nullable<int> TransID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> TransTime { get; set; }
        public Nullable<int> TransRegNo { get; set; }
        public Nullable<int> TransNumber { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> LocationNo { get; set; }
        public string LocationName { get; set; }
    
        public virtual ICollection<tCMSWeb_CM_TransactionFraud> tCMSWeb_CM_TransactionFraud { get; set; }
    }
}
