//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_CM_LossInjury_ContractorCharges
    {
        public int ContractorChargesID { get; set; }
        public Nullable<int> OfficeUseID { get; set; }
        public string CompanyName { get; set; }
        public string TypeOfWorkPerformed { get; set; }
        public string RequisitionNo { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual tCMSWeb_CM_LossInjury_OfficeUse tCMSWeb_CM_LossInjury_OfficeUse { get; set; }
    }
}
