//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCMSWeb_EX_ReportFilterFields
    {
        public tCMSWeb_EX_ReportFilterFields()
        {
            this.tCMSWeb_EX_MappingReportFilter = new HashSet<tCMSWeb_EX_MappingReportFilter>();
        }
    
        public int ReportFilterFieldID { get; set; }
        public string ReportFilterFieldName { get; set; }
        public string ReportFilterFieldValue { get; set; }
        public Nullable<bool> HasOperationCompare { get; set; }
        public Nullable<bool> isGroupField { get; set; }
    
        public virtual ICollection<tCMSWeb_EX_MappingReportFilter> tCMSWeb_EX_MappingReportFilter { get; set; }
    }
}
