//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRIPCamera
    {
        public tDVRIPCamera()
        {
            this.tDVRIPCameraInputs = new HashSet<tDVRIPCameraInput>();
            this.tDVRIPCameraUsers = new HashSet<tDVRIPCameraUser>();
        }
    
        public int KIPCamera { get; set; }
        public int KDVR { get; set; }
        public string MACAddress { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Port { get; set; }
        public string SubnetMask { get; set; }
        public string Gateway { get; set; }
        public Nullable<int> KIPModel { get; set; }
        public Nullable<long> ResolutionSupportedMask { get; set; }
        public string DisplayName { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual ICollection<tDVRIPCameraInput> tDVRIPCameraInputs { get; set; }
        public virtual tIPModel tIPModel { get; set; }
        public virtual ICollection<tDVRIPCameraUser> tDVRIPCameraUsers { get; set; }
    }
}
