//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRChangeHistory
    {
        public int KDVRHistory { get; set; }
        public int KDVR { get; set; }
        public System.DateTime DVRTime { get; set; }
        public int Time { get; set; }
        public string ChangeBy { get; set; }
        public Nullable<byte> ChangeFrom { get; set; }
        public string ChangeIP { get; set; }
        public byte KConfig { get; set; }
        public string Configuration { get; set; }
    
        public virtual tCMSConfigPage tCMSConfigPage { get; set; }
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
    }
}
