//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRUserPrivChannel
    {
        public int KUser { get; set; }
        public int KChannel { get; set; }
        public short KPrivilegeSearch { get; set; }
        public short KPrivilegeLive { get; set; }
        public int MaskSearch { get; set; }
        public int MaskLive { get; set; }
        public string DescriptionSearch { get; set; }
        public string DescriptionLive { get; set; }
    
        public virtual tI3Privileges tI3Privileges { get; set; }
        public virtual tDVRChannels tDVRChannels { get; set; }
        public virtual tDVRUsers tDVRUsers { get; set; }
    }
}
