//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRRestartTime
    {
        public int KDVR { get; set; }
        public short KDay { get; set; }
        public int Enable { get; set; }
        public int Hour { get; set; }
        public int Minute { get; set; }
        public Nullable<int> RestartMode { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual tWeek tWeek { get; set; }
    }
}
