//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRVLTrackers
    {
        public tDVRVLTrackers()
        {
            this.tDVRVLPoints = new HashSet<tDVRVLPoints>();
        }
    
        public int KVLTracker { get; set; }
        public int KChannel { get; set; }
        public short TrackerNo { get; set; }
        public int NumberOfPoint { get; set; }
        public Nullable<int> VLPolyType { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> AlarmType { get; set; }
        public Nullable<System.DateTime> BeginActiveTime { get; set; }
        public Nullable<System.DateTime> EndActiveTime { get; set; }
        public Nullable<int> IdleHour { get; set; }
        public Nullable<int> IdleMin { get; set; }
        public Nullable<int> IdleSec { get; set; }
        public Nullable<int> EnSendMail { get; set; }
        public Nullable<int> MissAlarm { get; set; }
        public string DefaultName { get; set; }
        public string CustomizedName { get; set; }
        public Nullable<int> EnAudio { get; set; }
        public Nullable<int> SoundDuration { get; set; }
        public string SoundFile { get; set; }
        public Nullable<int> ConditionNum { get; set; }
        public string Condition { get; set; }
        public Nullable<int> Extra1 { get; set; }
        public Nullable<int> Extra2 { get; set; }
    
        public virtual tDVRChannels tDVRChannels { get; set; }
        public virtual ICollection<tDVRVLPoints> tDVRVLPoints { get; set; }
    }
}
