//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRBookMark
    {
        public int KDVR { get; set; }
        public int KBookMark { get; set; }
        public decimal ChannelMask { get; set; }
        public long BmTime { get; set; }
        public string Description { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
    }
}
