//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRStorages
    {
        public int KDVR { get; set; }
        public string Drive { get; set; }
        public Nullable<int> TotalSpace { get; set; }
        public Nullable<int> FreeSpace { get; set; }
        public string VolumeName { get; set; }
        public Nullable<int> Use4Rec { get; set; }
        public Nullable<System.DateTime> StartRecDate { get; set; }
        public Nullable<System.DateTime> EndRecDate { get; set; }
        public Nullable<int> DriveType { get; set; }
        public Nullable<int> RecordDays { get; set; }
        public Nullable<decimal> ChannelMask { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
    }
}
