//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRDigitalMonitor
    {
        public tDVRDigitalMonitor()
        {
            this.tDVRDigitalMonitorOptions = new HashSet<tDVRDigitalMonitorOption>();
        }
    
        public long KMonitor { get; set; }
        public int KDVR { get; set; }
        public int MonitorNo { get; set; }
        public bool Enable { get; set; }
        public bool ShowInfo { get; set; }
    
        public virtual ICollection<tDVRDigitalMonitorOption> tDVRDigitalMonitorOptions { get; set; }
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
    }
}
