//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRVCScheduleDayRecords
    {
        public int KSchedule { get; set; }
        public int DayNo { get; set; }
        public int Id { get; set; }
        public long Time { get; set; }
        public long Begin { get; set; }
        public long End { get; set; }
        public int Type { get; set; }
    
        public virtual tDVRVCSchedules tDVRVCSchedules { get; set; }
    }
}
