//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVROSInfo
    {
        public int KDVR { get; set; }
        public string ComputerName { get; set; }
        public string UserName { get; set; }
        public string CPUModel { get; set; }
        public string TotalMemory { get; set; }
        public string FreeMemory { get; set; }
        public string OSPlatform { get; set; }
        public string OSVersion { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
    }
}
