//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRMotionConfig
    {
        public int KDVR { get; set; }
        public Nullable<int> RotateDwellTime { get; set; }
        public Nullable<int> Green { get; set; }
        public Nullable<int> DisplayMotion { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
    }
}
