//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRIZChannels
    {
        public int KChannel { get; set; }
        public bool Enable { get; set; }
        public int StartPresetPosition { get; set; }
        public int Sensitivity { get; set; }
        public int FreshTime { get; set; }
        public bool IsAdjustAllCamera { get; set; }
        public bool Is24Hour { get; set; }
        public int DwellTimeMovePreset { get; set; }
        public byte StartHour { get; set; }
        public byte StartMinute { get; set; }
        public byte StartSecond { get; set; }
        public byte EndHour { get; set; }
        public byte EndMinute { get; set; }
        public byte EndSecond { get; set; }
    
        public virtual tDVRChannels tDVRChannels { get; set; }
    }
}
