//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRControl
    {
        public int KDVR { get; set; }
        public int KIOCard { get; set; }
        public int KControl { get; set; }
        public int ControlNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> EnableControl { get; set; }
        public Nullable<long> BeginTime { get; set; }
        public Nullable<long> EndTime { get; set; }
        public Nullable<int> WorkingSec { get; set; }
        public decimal LinkWithChannel { get; set; }
        public decimal MotionMask { get; set; }
        public Nullable<int> RealIndex { get; set; }
        public Nullable<int> ControlType { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual tDVRIOCard tDVRIOCard { get; set; }
    }
}
