//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRVCChannels
    {
        public tDVRVCChannels()
        {
            this.tDVRVCSchedules = new HashSet<tDVRVCSchedules>();
        }
    
        public int KChannel { get; set; }
        public Nullable<int> Enable { get; set; }
        public Nullable<int> VideoSource { get; set; }
        public Nullable<int> Resolution { get; set; }
        public Nullable<int> FunctionType { get; set; }
        public Nullable<int> EnvType { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ControlOut { get; set; }
        public Nullable<int> NumOfTracker { get; set; }
    
        public virtual tDVRChannels tDVRChannels { get; set; }
        public virtual ICollection<tDVRVCSchedules> tDVRVCSchedules { get; set; }
    }
}
