//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRAddressBook
    {
        public tDVRAddressBook()
        {
            this.tDVRBookMarks = new HashSet<tDVRBookMark>();
            this.tDVRChangeHistories = new HashSet<tDVRChangeHistory>();
            this.tDVRConfigChangeTimes = new HashSet<tDVRConfigChangeTime>();
            this.tDVRConfigurationBackups = new HashSet<tDVRConfigurationBackup>();
            this.tDVRControls = new HashSet<tDVRControl>();
            this.tDVRIOCards = new HashSet<tDVRIOCard>();
            this.tDVRIPCameras = new HashSet<tDVRIPCameras>();
            this.tDVRLogContents = new HashSet<tDVRLogContent>();
            this.tDVRLogs = new HashSet<tDVRLog>();
            this.tDVRRestartTimes = new HashSet<tDVRRestartTime>();
            this.tDVRVideoSources = new HashSet<tDVRVideoSource>();
            this.tDVRRS232Ports = new HashSet<tDVRRS232Ports>();
            this.tDVRHWDigitalMonitors = new HashSet<tDVRHWDigitalMonitor>();
            this.tDVRDigitalMonitors = new HashSet<tDVRDigitalMonitor>();
            this.tCMSWeb_Audit = new HashSet<tCMSWeb_Audit>();
            this.tAlertEvent = new HashSet<tAlertEvent>();
            this.tDVRChannels = new HashSet<tDVRChannels>();
            this.tDVRResolutions = new HashSet<tDVRResolutions>();
            this.tDVRSensors = new HashSet<tDVRSensors>();
            this.tDVRUsers = new HashSet<tDVRUsers>();
            this.tDVRAnalogRes = new HashSet<tDVRAnalogRes>();
            this.tDVRStorages = new HashSet<tDVRStorages>();
        }
    
        public int KDVR { get; set; }
        public string DVRGuid { get; set; }
        public string ServerID { get; set; }
        public string ServerIP { get; set; }
        public Nullable<int> Online { get; set; }
        public string PublicServerIP { get; set; }
        public Nullable<int> TotalDiskSize { get; set; }
        public Nullable<int> FreeDiskSize { get; set; }
        public string DVRAlias { get; set; }
        public Nullable<int> RecordingDay { get; set; }
        public Nullable<System.DateTime> FirstAccess { get; set; }
        public Nullable<System.DateTime> TimeDisConnect { get; set; }
        public Nullable<short> CMSMode { get; set; }
        public Nullable<int> LastConnectTime { get; set; }
        public Nullable<int> CurConnectTime { get; set; }
        public Nullable<int> KDVRVersion { get; set; }
        public string HaspLicense { get; set; }
    
        public virtual tbl_POS_PACID tbl_POS_PACID { get; set; }
        public virtual tDVRVersion tDVRVersion { get; set; }
        public virtual tDVRBackupSchedule tDVRBackupSchedule { get; set; }
        public virtual ICollection<tDVRBookMark> tDVRBookMarks { get; set; }
        public virtual ICollection<tDVRChangeHistory> tDVRChangeHistories { get; set; }
        public virtual ICollection<tDVRConfigChangeTime> tDVRConfigChangeTimes { get; set; }
        public virtual ICollection<tDVRConfigurationBackup> tDVRConfigurationBackups { get; set; }
        public virtual ICollection<tDVRControl> tDVRControls { get; set; }
        public virtual tDVRHardware tDVRHardware { get; set; }
        public virtual ICollection<tDVRIOCard> tDVRIOCards { get; set; }
        public virtual ICollection<tDVRIPCameras> tDVRIPCameras { get; set; }
        public virtual tDVRKeepAlives tDVRKeepAlife { get; set; }
        public virtual ICollection<tDVRLogContent> tDVRLogContents { get; set; }
        public virtual ICollection<tDVRLog> tDVRLogs { get; set; }
        public virtual tDVRMotionConfig tDVRMotionConfig { get; set; }
        public virtual tDVRNetwork tDVRNetwork { get; set; }
        public virtual tDVRServerInfo tDVRServerInfo { get; set; }
        public virtual tDVROSInfo tDVROSInfo { get; set; }
        public virtual ICollection<tDVRRestartTime> tDVRRestartTimes { get; set; }
        public virtual tDVRStorageConfig tDVRStorageConfig { get; set; }
        public virtual tDVRSystemInfo tDVRSystemInfo { get; set; }
        public virtual tDVRTextOverlayConfig tDVRTextOverlayConfig { get; set; }
        public virtual tDVRUserConfig tDVRUserConfig { get; set; }
        public virtual ICollection<tDVRVideoSource> tDVRVideoSources { get; set; }
        public virtual ICollection<tDVRRS232Ports> tDVRRS232Ports { get; set; }
        public virtual ICollection<tDVRHWDigitalMonitor> tDVRHWDigitalMonitors { get; set; }
        public virtual ICollection<tDVRDigitalMonitor> tDVRDigitalMonitors { get; set; }
        public virtual ICollection<tCMSWeb_Audit> tCMSWeb_Audit { get; set; }
        public virtual ICollection<tAlertEvent> tAlertEvent { get; set; }
        public virtual ICollection<tDVRChannels> tDVRChannels { get; set; }
        public virtual ICollection<tDVRResolutions> tDVRResolutions { get; set; }
        public virtual ICollection<tDVRSensors> tDVRSensors { get; set; }
        public virtual tDVRTimeAttributes tDVRTimeAttributes { get; set; }
        public virtual ICollection<tDVRUsers> tDVRUsers { get; set; }
        public virtual ICollection<tDVRAnalogRes> tDVRAnalogRes { get; set; }
        public virtual ICollection<tDVRStorages> tDVRStorages { get; set; }
        public virtual tDVREmail tDVREmail { get; set; }
    }
}
