//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRChannels
    {
        public tDVRChannels()
        {
            this.tCMSWeb_Audit_Media = new HashSet<tCMSWeb_Audit_Media>();
            this.tDVRRecordSchedule = new HashSet<tDVRRecordSchedule>();
            this.tDVRUserPrivChannel = new HashSet<tDVRUserPrivChannel>();
            this.tDVRVLTrackers = new HashSet<tDVRVLTrackers>();
            this.tCMSWeb_Audit = new HashSet<tCMSWeb_Audit>();
            this.tDVRVPTrackers = new HashSet<tDVRVPTrackers>();
            this.tDVRIGTrackers = new HashSet<tDVRIGTrackers>();
            this.tDVRIZTrackers = new HashSet<tDVRIZTrackers>();
            this.tDVRMotionTrackers = new HashSet<tDVRMotionTrackers>();
            this.tDVRTextOverlayTrackers = new HashSet<tDVRTextOverlayTrackers>();
            this.tDVRVCTrackers = new HashSet<tDVRVCTrackers>();
            this.tCMSWebSites = new HashSet<tCMSWebSites>();
            this.tbl_HM_TaskChannel = new HashSet<tbl_HM_TaskChannel>();
        }
    
        public int ChannelNo { get; set; }
        public int KDVR { get; set; }
        public int KChannel { get; set; }
        public Nullable<int> VideoSource { get; set; }
        public int KAudioSource { get; set; }
        public int KPTZ { get; set; }
        public Nullable<int> Status { get; set; }
        public string Name { get; set; }
        public Nullable<int> Enable { get; set; }
        public Nullable<int> DwellTime { get; set; }
        public Nullable<int> AP { get; set; }
        public Nullable<int> CameraID { get; set; }
        public Nullable<int> VideoCompressQual { get; set; }
        public Nullable<int> VideoType { get; set; }
        public Nullable<int> KVideo { get; set; }
        public bool EnableiSearch { get; set; }
        public Nullable<bool> EnableTrafficCount { get; set; }
    
        public virtual ICollection<tCMSWeb_Audit_Media> tCMSWeb_Audit_Media { get; set; }
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual tPTZType tPTZType { get; set; }
        public virtual ICollection<tDVRRecordSchedule> tDVRRecordSchedule { get; set; }
        public virtual ICollection<tDVRUserPrivChannel> tDVRUserPrivChannel { get; set; }
        public virtual tDVRVirtualRuler tDVRVirtualRuler { get; set; }
        public virtual ICollection<tDVRVLTrackers> tDVRVLTrackers { get; set; }
        public virtual ICollection<tCMSWeb_Audit> tCMSWeb_Audit { get; set; }
        public virtual tDVRVPChannels tDVRVPChannels { get; set; }
        public virtual ICollection<tDVRVPTrackers> tDVRVPTrackers { get; set; }
        public virtual tDVRIGChannel tDVRIGChannel { get; set; }
        public virtual ICollection<tDVRIGTrackers> tDVRIGTrackers { get; set; }
        public virtual tDVRIZChannels tDVRIZChannels { get; set; }
        public virtual ICollection<tDVRIZTrackers> tDVRIZTrackers { get; set; }
        public virtual ICollection<tDVRMotionTrackers> tDVRMotionTrackers { get; set; }
        public virtual tDVRTextOverlayChannels tDVRTextOverlayChannels { get; set; }
        public virtual ICollection<tDVRTextOverlayTrackers> tDVRTextOverlayTrackers { get; set; }
        public virtual tDVRVCChannels tDVRVCChannels { get; set; }
        public virtual ICollection<tDVRVCTrackers> tDVRVCTrackers { get; set; }
        public virtual tDVRVLChannels tDVRVLChannels { get; set; }
        public virtual ICollection<tCMSWebSites> tCMSWebSites { get; set; }
        public virtual ICollection<tbl_HM_TaskChannel> tbl_HM_TaskChannel { get; set; }
    }
}
