//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRVirtualRuler
    {
        public int KChannel { get; set; }
        public int Color { get; set; }
        public short KUnit { get; set; }
        public int StartX { get; set; }
        public int StartY { get; set; }
        public int EndX { get; set; }
        public int EndY { get; set; }
        public bool EnableLiveMode { get; set; }
        public double StartPoint { get; set; }
        public double EndPoint { get; set; }
        public double LengthOfDivision { get; set; }
    
        public virtual tRulerUnit tRulerUnit { get; set; }
        public virtual tDVRChannels tDVRChannels { get; set; }
    }
}
