//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVREmail
    {
        public int KDVR { get; set; }
        public bool Enable { get; set; }
        public bool EnableVLoss { get; set; }
        public int Threshold { get; set; }
        public int TransmissionDelay { get; set; }
        public string ToAddress { get; set; }
        public string FromAddress { get; set; }
        public string FromName { get; set; }
        public string SMTPIP { get; set; }
        public int SMTPPort { get; set; }
        public short KSMTPLoginMethod { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
        public bool ServerStatusSendEmail { get; set; }
        public int ServerStatusChannelImage { get; set; }
        public int ServerStatusSendEmailEvery { get; set; }
        public string ServerStatusEmailTitle { get; set; }
        public Nullable<int> VideoLossDwelltime { get; set; }
    
        public virtual tSMTPLoginMethod tSMTPLoginMethod { get; set; }
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
    }
}
