//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRNetworkCard
    {
        public int KDVR { get; set; }
        public int NetworkCardID { get; set; }
        public string AdapterName { get; set; }
        public string Description { get; set; }
        public string MACAddress { get; set; }
        public string IPv4List { get; set; }
        public string Gatewayv4List { get; set; }
        public string DNSv4List { get; set; }
        public string IPv6List { get; set; }
        public string Gatewayv6List { get; set; }
        public string DNSv6List { get; set; }
    }
}
