//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRDigitalMonitorOption
    {
        public tDVRDigitalMonitorOption()
        {
            this.tDVRDigitalMonitorChannels = new HashSet<tDVRDigitalMonitorChannel>();
        }
    
        public long KOption { get; set; }
        public long KMonitor { get; set; }
        public string OptName { get; set; }
        public Nullable<int> Enable { get; set; }
        public Nullable<int> DwellTime { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Stream { get; set; }
        public Nullable<int> DisplayLayout { get; set; }
    
        public virtual tDVRDigitalMonitor tDVRDigitalMonitor { get; set; }
        public virtual ICollection<tDVRDigitalMonitorChannel> tDVRDigitalMonitorChannels { get; set; }
    }
}
