//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRIZTrackers
    {
        public int KTracker { get; set; }
        public int KChannel { get; set; }
        public int PercentOfChanges { get; set; }
        public string AreaName { get; set; }
        public int StartX { get; set; }
        public int StartY { get; set; }
        public short Width { get; set; }
        public short Height { get; set; }
        public short PresetID { get; set; }
        public int DwellTime { get; set; }
        public int Priority { get; set; }
        public short ControlOutput { get; set; }
        public short RelativeCameraID { get; set; }
        public short RelativeResetID { get; set; }
    
        public virtual tDVRChannels tDVRChannels { get; set; }
    }
}
