//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRDigitalMonitorChannel
    {
        public long KOption { get; set; }
        public int ChannelNo { get; set; }
        public int Position { get; set; }
    
        public virtual tDVRDigitalMonitorOption tDVRDigitalMonitorOption { get; set; }
    }
}
