//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRVideoSource
    {
        public int KVideoSource { get; set; }
        public int KDVR { get; set; }
        public int VideoSourceNo { get; set; }
        public Nullable<int> Brightness { get; set; }
        public Nullable<int> Contrast { get; set; }
        public Nullable<int> Hue { get; set; }
        public Nullable<int> Monochrome { get; set; }
        public Nullable<int> FPS { get; set; }
        public Nullable<short> KResolution { get; set; }
        public Nullable<int> Emergency { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> ResolutionWidth { get; set; }
        public Nullable<int> ResolutionHeight { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual tResolutionDef tResolutionDef { get; set; }
    }
}
