//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRResolutions
    {
        public int KDVR { get; set; }
        public short KResolution { get; set; }
        public int TotalFrame { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual tResolutionDef tResolutionDef { get; set; }
    }
}
