//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRUserConfig
    {
        public int KDVR { get; set; }
        public Nullable<int> EnableAutoLogOut { get; set; }
        public Nullable<int> TimeOutLogOut { get; set; }
        public Nullable<int> LDAPEnable { get; set; }
        public string LDAPServer { get; set; }
        public string LDAPUsername { get; set; }
        public string LDAPPassword { get; set; }
        public Nullable<int> LDAPUseSSL { get; set; }
        public Nullable<int> LDAPSyncInterval { get; set; }
        public Nullable<int> LDAPPort { get; set; }
        public Nullable<int> LDAPLimitEntryNumer { get; set; }
        public string LDAPGroupDN { get; set; }
        public string LDAPUserDN { get; set; }
        public Nullable<int> LDAPServerType { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
    }
}
