//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRServerInfo
    {
        public int KDVR { get; set; }
        public string Version { get; set; }
        public string DvrName { get; set; }
        public string Location { get; set; }
        public string Model { get; set; }
        public string UserName { get; set; }
        public string PACID { get; set; }
        public string Distributor { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> Display { get; set; }
        public string KLanguage { get; set; }
        public string ServerIPv6 { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual tLanguage tLanguage { get; set; }
    }
}
