//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRTextOverlayChannels
    {
        public int KChannel { get; set; }
        public int ScrollDelay { get; set; }
        public int TextDelay { get; set; }
        public bool Disable { get; set; }
        public int Brightness { get; set; }
        public int ShowColorMode { get; set; }
    
        public virtual tDVRChannels tDVRChannels { get; set; }
    }
}
