//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRUsers
    {
        public tDVRUsers()
        {
            this.tDVRUserPrivChannel = new HashSet<tDVRUserPrivChannel>();
            this.tDVRUserPrivOp = new HashSet<tDVRUserPrivOp>();
            this.tDVRUserPrivSetup = new HashSet<tDVRUserPrivSetup>();
        }
    
        public int KUser { get; set; }
        public int KDVR { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Usertype { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual ICollection<tDVRUserPrivChannel> tDVRUserPrivChannel { get; set; }
        public virtual ICollection<tDVRUserPrivOp> tDVRUserPrivOp { get; set; }
        public virtual ICollection<tDVRUserPrivSetup> tDVRUserPrivSetup { get; set; }
    }
}
