//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRVLSchedules
    {
        public tDVRVLSchedules()
        {
            this.tDVRVLScheduleDayRecords = new HashSet<tDVRVLScheduleDayRecords>();
        }
    
        public int KSchedule { get; set; }
        public int KChannel { get; set; }
        public int ScheduleNo { get; set; }
        public string Name { get; set; }
        public long Time { get; set; }
        public int RotationType { get; set; }
        public int Size { get; set; }
    
        public virtual tDVRVLChannels tDVRVLChannels { get; set; }
        public virtual ICollection<tDVRVLScheduleDayRecords> tDVRVLScheduleDayRecords { get; set; }
    }
}
