//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRIOCard
    {
        public tDVRIOCard()
        {
            this.tDVRControls = new HashSet<tDVRControl>();
            this.tDVRSensors = new HashSet<tDVRSensors>();
        }
    
        public int KDVR { get; set; }
        public int KIOCard { get; set; }
        public int CardType { get; set; }
        public int NumberSensors { get; set; }
        public int NumberControls { get; set; }
        public Nullable<bool> MonitorSupport { get; set; }
        public Nullable<bool> PTZSupport { get; set; }
        public Nullable<bool> WatchDogSupport { get; set; }
        public string COMPortName { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string IOname { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual ICollection<tDVRControl> tDVRControls { get; set; }
        public virtual ICollection<tDVRSensors> tDVRSensors { get; set; }
    }
}
