//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRVPPoints
    {
        public int KVPTracker { get; set; }
        public int VPPointIndex { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
    
        public virtual tDVRVPTrackers tDVRVPTrackers { get; set; }
    }
}
