//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRHWDigitalMonitor
    {
        public int KDVR { get; set; }
        public int MonitorNo { get; set; }
        public string OptName { get; set; }
        public Nullable<int> EnableOpt { get; set; }
        public Nullable<int> DwellTime { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Stream { get; set; }
        public Nullable<decimal> ChannelMask { get; set; }
        public Nullable<bool> EnableMonitor { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
    }
}
