//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRUserOperation
    {
        public tDVRUserOperation()
        {
            this.tDVRUserPrivOps = new HashSet<tDVRUserPrivOp>();
        }
    
        public int KOp { get; set; }
        public string OpName { get; set; }
    
        public virtual ICollection<tDVRUserPrivOp> tDVRUserPrivOps { get; set; }
    }
}
