//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRTimeAttributes
    {
        public int KDVR { get; set; }
        public short KDateFormat { get; set; }
        public short KTimeFormat { get; set; }
    
        public virtual tDateFormat tDateFormat { get; set; }
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual tTimeFormat tTimeFormat { get; set; }
    }
}
