//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRLDAPGroup
    {
        public int KGroup { get; set; }
        public int KDVR { get; set; }
        public string Profile { get; set; }
        public string Group { get; set; }
    }
}
