//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRUserPrivOp
    {
        public int KUser { get; set; }
        public int KOp { get; set; }
        public int KPrivilege { get; set; }
        public int Mask { get; set; }
        public string Description { get; set; }
    
        public virtual tDVRUserOperation tDVRUserOperation { get; set; }
        public virtual tDVRUsers tDVRUsers { get; set; }
    }
}
