//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRSystemInfo
    {
        public int KDVR { get; set; }
        public int EnSyncNTP { get; set; }
        public int SyncNTPHour { get; set; }
        public int SyncNTPMinute { get; set; }
        public int EnControlVLoss { get; set; }
        public int EnAlarmVLoss { get; set; }
        public int ControlVLoss { get; set; }
        public int AlarmHourVLoss { get; set; }
        public int AlarmMinVLoss { get; set; }
        public int AlarmSecVLoss { get; set; }
        public int AutoLogonOS { get; set; }
        public string OSUserName { get; set; }
        public string OSPassword { get; set; }
        public int EnWatermark { get; set; }
        public int DisplayWatermark { get; set; }
        public int BaudratePTZ { get; set; }
        public Nullable<int> KPort { get; set; }
        public int ActiveSensorWaitTime { get; set; }
        public Nullable<int> ActiveSensorExportType { get; set; }
        public string ActiveSensorDestName { get; set; }
        public string ActiveSensorEmail { get; set; }
        public Nullable<int> ActiveSensorCopies { get; set; }
        public Nullable<int> ActiveSensorVideoFormat { get; set; }
        public Nullable<decimal> ActiveSensorChannelMask { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual tDVRRS232Ports tDVRRS232Ports { get; set; }
    }
}
