//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRIPCameraInputs
    {
        public tDVRIPCameraInputs()
        {
            this.tDVRIPRes = new HashSet<tDVRIPRes>();
        }
    
        public int KDVRIPCamera { get; set; }
        public int KIPCamera { get; set; }
        public Nullable<int> InputNo { get; set; }
        public Nullable<int> VideoChannelNo { get; set; }
        public Nullable<int> FrameRate { get; set; }
        public Nullable<short> KResolution { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> MaxFPS { get; set; }
        public Nullable<int> ResolutionWidth { get; set; }
        public Nullable<int> ResolutionHeight { get; set; }
        public string AdapterName { get; set; }
        public string ResWidthtMask { get; set; }
        public string ResHeightMask { get; set; }
    
        public virtual tDVRIPCameras tDVRIPCameras { get; set; }
        public virtual tResolutionDef tResolutionDef { get; set; }
        public virtual ICollection<tDVRIPRes> tDVRIPRes { get; set; }
    }
}
