//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVRNetwork
    {
        public int KDVR { get; set; }
        public int KNetworkType { get; set; }
        public int KBandwidth { get; set; }
        public int ControlPort { get; set; }
        public int TextOverlayPort { get; set; }
        public int LiveSearchPort { get; set; }
        public int PACDBPort { get; set; }
        public int BackupPort1 { get; set; }
        public Nullable<int> BackupPort2 { get; set; }
        public Nullable<int> BackupPort3 { get; set; }
        public Nullable<int> CMSServerPort { get; set; }
        public Nullable<int> MobileMainPort { get; set; }
        public Nullable<int> MobileVideoPort { get; set; }
        public Nullable<int> MobileKeepEventLog { get; set; }
    
        public virtual tDVRAddressBook tDVRAddressBook { get; set; }
        public virtual tNetworkType tNetworkType { get; set; }
    }
}
