//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tI3Privileges
    {
        public tI3Privileges()
        {
            this.tDVRUserPrivChannels = new HashSet<tDVRUserPrivChannel>();
            this.tDVRUserPrivSetups = new HashSet<tDVRUserPrivSetup>();
        }
    
        public short KPrivilege { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tDVRUserPrivChannel> tDVRUserPrivChannels { get; set; }
        public virtual ICollection<tDVRUserPrivSetup> tDVRUserPrivSetups { get; set; }
    }
}
