//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIPModel
    {
        public tIPModel()
        {
            this.tDVRIPCameras = new HashSet<tDVRIPCameras>();
        }
    
        public int KIPModel { get; set; }
        public string ModelName { get; set; }
        public int VideoCount { get; set; }
        public Nullable<int> AudioCount { get; set; }
        public Nullable<int> SensorCount { get; set; }
        public Nullable<int> ControlCount { get; set; }
    
        public virtual ICollection<tDVRIPCameras> tDVRIPCameras { get; set; }
    }
}
