//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLanguage
    {
        public tLanguage()
        {
            this.tDVRServerInfo = new HashSet<tDVRServerInfo>();
        }
    
        public string KLanguage { get; set; }
        public string Language { get; set; }
    
        public virtual ICollection<tDVRServerInfo> tDVRServerInfo { get; set; }
    }
}
