//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNetworkType
    {
        public tNetworkType()
        {
            this.tDVRNetworks = new HashSet<tDVRNetwork>();
        }
    
        public int KNetworkType { get; set; }
        public string NetworkTypeName { get; set; }
    
        public virtual ICollection<tDVRNetwork> tDVRNetworks { get; set; }
    }
}
