//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPTZType
    {
        public tPTZType()
        {
            this.tDVRChannels = new HashSet<tDVRChannels>();
        }
    
        public int KPTZ { get; set; }
        public string PTZName { get; set; }
    
        public virtual ICollection<tDVRChannels> tDVRChannels { get; set; }
    }
}
