//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tResolutionDef
    {
        public tResolutionDef()
        {
            this.tDVRVideoSources = new HashSet<tDVRVideoSource>();
            this.tDVRIPCameraInputs = new HashSet<tDVRIPCameraInputs>();
            this.tDVRResolutions = new HashSet<tDVRResolutions>();
        }
    
        public short KResolution { get; set; }
        public short KVideoFormat { get; set; }
        public string Resolution { get; set; }
        public Nullable<short> ResolutionNo { get; set; }
    
        public virtual ICollection<tDVRVideoSource> tDVRVideoSources { get; set; }
        public virtual tVideoFormat tVideoFormat { get; set; }
        public virtual ICollection<tDVRIPCameraInputs> tDVRIPCameraInputs { get; set; }
        public virtual ICollection<tDVRResolutions> tDVRResolutions { get; set; }
    }
}
