//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSMTPLoginMethod
    {
        public tSMTPLoginMethod()
        {
            this.tDVREmails = new HashSet<tDVREmail>();
        }
    
        public short KMethod { get; set; }
        public string MethodName { get; set; }
    
        public virtual ICollection<tDVREmail> tDVREmails { get; set; }
    }
}
