//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSystemTypes
    {
        public tSystemTypes()
        {
            this.tCMSSystemStatus = new HashSet<tCMSSystemStatus>();
        }
    
        public int KSystemType { get; set; }
        public string SystemType { get; set; }
    
        public virtual ICollection<tCMSSystemStatus> tCMSSystemStatus { get; set; }
    }
}
