//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTimeZone
    {
        public int KSystem { get; set; }
        public string TimeZoneName { get; set; }
        public double TimeZoneOffset { get; set; }
        public int SystemType { get; set; }
    }
}
