//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVideoFormat
    {
        public tVideoFormat()
        {
            this.tResolutionDefs = new HashSet<tResolutionDef>();
        }
    
        public short KVideoFormat { get; set; }
        public string Format { get; set; }
    
        public virtual ICollection<tResolutionDef> tResolutionDefs { get; set; }
    }
}
