//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CMSWeb_DVRFollowUser
    {
        public int UserID { get; set; }
        public int siteKey { get; set; }
        public int KDVR { get; set; }
        public int KChannel { get; set; }
        public int PACID { get; set; }
    }
}
