//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CMSWeb_Function_Level
    {
        public int FunctionID { get; set; }
        public string FunctionName { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public int LevelID { get; set; }
        public string LevelName { get; set; }
        public int FunclevelID { get; set; }
    }
}
