//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DVR_PAC_Channels
    {
        public int KDVR { get; set; }
        public int KChannel { get; set; }
        public int ChannelNo { get; set; }
        public string Name { get; set; }
        public Nullable<bool> EnableTrafficCount { get; set; }
        public int PCamID { get; set; }
        public int DimCam { get; set; }
        public Nullable<int> PCamName { get; set; }
        public int DimPACID { get; set; }
    }
}
