//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Channels_Resolutions
    {
        public int KDVR { get; set; }
        public int ChannelNo { get; set; }
        public int KChannel { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public int FPS { get; set; }
        public string Resolution { get; set; }
        public int isAnalog { get; set; }
        public string ModelName { get; set; }
    }
}
