//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACDMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Fact_IOPC_Count
    {
        public Nullable<int> C_CameraNumber { get; set; }
        public string Location { get; set; }
        public Nullable<int> AreaName { get; set; }
        public string C_AreaName { get; set; }
        public string C_ObjectType { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> DVRHour { get; set; }
        public Nullable<System.DateTime> DVRDateKey { get; set; }
        public int T_PACID { get; set; }
        public Nullable<long> C_Count { get; set; }
        public Nullable<System.DateTime> DVRDate { get; set; }
    }
}
